### ISSUE TITLE
Summer is coming

### ISSUE THREAD

**Issue by UralZima** [edannenberg/kubler#102]
Hey guys. ~~I just smoked a little bit of wee...~~ well, got some cool ideas about your project :)
I think we can turn it into very smart server manager, and just in some more bash oneliners included. 
I want to describe a little bit my experience from using this project since Nov 2016 on a production server, serving high-load web-sites. I hope you will find something interesting in this long post.

I am an perfectionist, and like all to be secure, high-tech and best and the only way, best and latest opensource world offers. I am using linux since 2002 and tried different server setups, OSes, virtual machines, kvm, lxc, etc. And all resulted to this:

Libreboot instead of BIOS/EFI. Asus KGPE-D16.
2 x AMD 12-core
128GB ECC Ram
3 x SSD 512GB
3 x HDD 4TB
Gentoo. Only. Hardened with grsecurity, GCC5.4.1, latest hardened-sources with proper configuration and deblob. Only GPL code on whole system. -fPIE
ZFS. The best and stablest filesystem.

ZFS is on top of LUKS. 3 X SSD, every is on LUKS, unlocked by one key. ZFS mirrors 3 SSD on top of LUKS into one filesystem, used for booting and running rootfs on it.
3 X HDD, each on LUKS partition are unified into another ZFS mirror pool. This is used for audio/video storage. 
ZFS compression=lz4 - compressing/decopressing faster, than SATA III, cpu accelerated. Increasing read and write performance much. 
zfs copies=2 for sensitive data partitions.

All LUKS partitions are unlocked once on boot using dropbear ssh daemon inside initramfs. A bash script, extracts initramfs, adds dropbear, ifconfig and others and pack it back. 
Server is unlocked issuing one ssh command on admin machine. 
Encryption is very fast, using cpu instructions, no performance slowdown.
ZFS partitions are divided into groups, which are important files, and second is /tmp, /usr/portage , /var/tmp and /var/cache group. They don't need to be snapshotted/backuped. zsnap snapshots important partition every hour and week. Deletes OLD. ALL filesystems are sent to backup host lively. Second host contains full actual mirror of the first server and can run it easily. Next release ZFS on Linux will have TRIM and native encryption support. I use it 2 years on all systems and it is the most stable fs I used. Currently 0.6.5.9 version.

APPARMOR by default. The best user-space security tool, well working with grsecurity and docker.

DOCKER. One service per container separate for every site. Working the best with ZFS.

And of course, the leader of all this is GENTOOBB!
The hardest part and longest part... but, I know how to make life much easier, than doing all this manually:

1. Learning. Many learning with a bit of lack of documentation, but very user-friendly community and fast fixes.
2. Always modifying config files, specifying very long path to vim command.
3. Always thinking how to fix multiple new/modified packages, issuing multiple repeated bash oneliners
4. It took me one month to build what I want and be sure it can be used in production.
5. When I am rebuilding anything/updating/incl version of gentoobb, I need to be sure new packages can replace running containers, created from old images, and new will work well and can be replaced lively for all high-load web sites, removing old containers and recreating them with long-long presaved command, that uses blk and cpu priorities, attaching /hdd and all data folders. 

First, I create duplicate gentoobb folder and use a new one, especially when updating to newer versions. Inside it, I rename the namespace, modify it including previous errors/forgot things, and build all packages in new namespace. They are:
bind, php7 (separately from nginx), nginx + pagespeed, mariadb, redis, django, ffmpeg.
For mail server, I use iRedmail with baseimage. This is best you can get now.
Each site have own nginx, multiple php7 containers and separate mariadb instances. Piwik and Livehelperchat have separate php7 instances for security. nginx have access to all. Everything connected through socked dir sharing. For each site. We use cpu and blk pririties to all containers, for sites needed 100% fastest responce, than others, not being depend from that. 

After building a new namespace, I run some testing, executing each container using some good zsh aliases:

de () {docker exec -it $1 bash} # execute bash in given container
dr () {docker run --name tmp $2 $3 -it $1 bash; docker rm -f tmp} # run a test instance and remove it when exit.
alias dshit='docker rmi $(docker images -f "dangling=true" -q)' # remove garbage images
alias ds='docker stats $(docker ps --format '{{.Names}}')' #nice stats

After I am sure all new packages run fine, I am executing such script:

sed 's/oldnamespace/newnamespace/g' /path/to/bash/script/for/creating/all/containers
docker rm -f $(docker ps -q)
./create_and_run_containers.sh #from new namespace
docker rmi -f $(docker images | grep 'oldnamespace/' | awk '{print $1 ":" $2}')
Now I have new images using in production, and deleted anything old. 
Upgrade took 3-5 sec of downtime. 

## Example docker run commands: 

docker run --restart=unless-stopped --blkio-weight 800 -c 1024 -d -h sitename-nginx --name sitename-nginx -v /d/hdd:/hdd -v /d/www/sitename/htdocs:/www/htdocs -v /d/www/stats/htdocs:/www/htdocs/stats -v /d/www/chat/htdocs:/www/htdocs/chat -v /d/www/sitename/nginx:/etc/nginx -v /d/www/sitename/sockets/php:/var/run/php-sitename -v /d/www/chat/sockets/php:/var/run/php-chat -v /d/www/stats/sockets/php:/var/run/php-stats  -p 80:80 -p 443:443 w/nginx

docker run --restart=unless-stopped --blkio-weight 900 -c 1024 --cap-add=SYS_NICE --device /dev/dri:/dev/dri -d --name sitename-php -h sitename-php -v /d/hdd:/hdd  -v /d/www/sitename/php-fpm:/etc/php/fpm-php7.1 -v /d/www/sitename/htdocs:/www/htdocs -v /d/www/sitename/sockets/mysql:/var/run/mysqld -v /d/www/sitename/sockets/php:/var/run/php w/php7

docker run --restart=unless-stopped --blkio-weight 1000 -c 1024 -d -h sitename-db --name sitename-db -v /d/www/sitename/my.cnf:/etc/mysql/my.cnf -v /d/www/sitename/mysql:/var/lib/mysql/ -v /d/www/sitename/sockets/mysql:/var/run/mysqld -e BACKUP_CRON_SCHEDULE='0 2 * * *' -v /d/www/sitename/backups:/backup w/mariadb

All built with -march=native, increasing binaries performance a lot, especially for php and ffmpeg.

## The future

Every time I worked with gentoobb, I missed this nice and easy to implement features. I think these oneliners may be integrated into omnibob multicall executable. 

* `virsh edit/create` equvalent. I created a symlink 'i' pointing to dock/namespace/images to make life easier, but not enough. I want to be able to create a new package with 

* ./omnibob new ffmpeg, getting me into vim and a new template file, unified syntax-changed Dockerfile.template, build.sh and build.conf. Multiple comments, saying about each section and offering examples. It creates a new folder, config files. It unmasks all packages that depend, predefining flaggie commands.
I think you may not specify namespace if you call an omnibob binary from /usr/local/bin inside namespace folder. 

* omnibob edit ffmpeg - open vim and edit unified config file. Just like virsh. Syntax check.
* omnibob test ffmpeg - build interactive, remove leftovers
* omnibob build ffmpeg - build image. also remove all failed leftover containers.
* omnibob rebuild ffmpeg - rebuilds same image. Must delete created container right before building finishes, to successfully replace image. Recreate container from some config/xml file. 
* omnibob replace -f oldnamespace -t newnamespace - builds and replace running containers, with -d may delete old namespace. Live system upgrade.
* omnibob top - ds alias

Also I use Nagios to monitor all services in all containers.

I think if we can automate such user-friendly functions, we can made an ultimate best server  configuration guide, describing this all in a tutorial and use omnibob as cover for all managing and docker. It may be a higher-level docker frontend. 

We must involve new people, students and system administors follow this way, and get rid of crappy ubuntu and centos, being their slaves and use only how they decided, including crappy systemd. If you want to earn highest possible salary and receive pleasure and satisfaction from your work, use Gentoo GNU/Linux, ZFS, Docker, Omnibob, Live replication, nginx instead apache :) + pagespeed

I think we can find many new followers from production world, and many contributions, because we (will) make life easier, managing the server in general and be sure, it is the best secure and hardware-accelerated way. It is not a crappy YaST ;)

We can even create an ISO, which is doing all that in interactive way, OmniGNULinux :)

Thanks for attention.

P.S. I use Plasma 5.9.3 on my gentoo localhost. The best and stable DE I used and Kdevelop for developing. Also KDE includes fish protocol, which allows you to edit any file in favorite KATE/Kdevelop editor lively through ssh, and save it, using path fish://remote_ssh/root/gentoobb/build.conf

**Comment by edannenberg** [comment]
Thanks for this long write up and grats on your setup. Always nice to read. I'm a bit short on time currently so only a quick response for now, I'll digest this in full later:

1. A lot of your suggestions are out of scope. All this project is meant to do is build images and push 'em some place. Unix philosophy and all that. There are already plenty of solutions that do the container deploy/management part perfectly fine. Testing images is planned though.

2. I would strongly recommend to utilize git for your workflow, ideally:

* Don't build on the production servers, I understand you want `native` gcc flags, so I would go for a separate build server with the same cpu specs as production. Maybe you already do that, just making sure. :P
* Setup a private docker registry to hold your images
* Create a github private repo or setup your own [Gitlab](https://about.gitlab.com/) on a separate server, there are ready made docker images for the latter so it's quick and painless
* Create your own namespace directory and put that into your git. This way your images are neatly separated and you can extend from any of the example images. Updates are then a matter of running `git pull` and having a quick look at the changelog/past commits.
* Edit your image files locally, then commit and push to your repo. Setup CI on github or gitlab that triggers a rebuild on your build server, runs tests, etc when you push changes to your git repo. The [webhook](https://github.com/edannenberg/gentoo-bb/tree/master/dock/gentoobb/images/webhook) image is handy for acting on github/gitlab push events.
* Then it's just matter of pulling the tested images on your production servers

Just my 2 cents as I don't know all the details of your pretty specialized setup. As always it depends. I'll guarantee you though that one day after using git you will ask yourself why you didn't do this sooner. :) 

> Offtopic: invitation to gentoobb project discussion, which uses Docker as engine docker/docker

I appreciate your enthusiasm for spreading the word but the timing is not the best. Once the spring branch is live, with the new project name and decent docs, would be a much better time for such a post.

**Comment by edannenberg** [comment]
Probably relevant to your interests, you can now drop your own scripts into the `./lib/cmd/` folder that can utilize Kubler's functions:

```bash
#!/usr/bin/env bash

function main() {
    echo "kubler dir: ${_KUBLERDIR}"
    echo "current namespace: ${_NAMESPACE_DIR}"
    echo "here be dragons!"
}

main "$@"
```

Assuming the above script is named `deploy.sh` you could then invoke it by running `kubler deploy`. Hope that helps a bit.
