### ISSUE TITLE
Questions about glibc image

### ISSUE THREAD

**Issue by azimut** [edannenberg/kubler#111]
* https://github.com/edannenberg/gentoo-bb/blob/kubler/dock/kubler/images/glibc/build.sh#L29
I think the lib64 -> lib symlink should belong to build-root.sh. Any reason is not there?. I am thinking about it for musl support.
* https://github.com/edannenberg/gentoo-bb/blob/kubler/dock/kubler/images/glibc/build.sh#L33
What is the relevance of this? I see the namespace hard-coded there. What if I use a different namespace name? I will be losing something?

PS: I will have more time to play with this on the weekend. Thus far I have been busy trying to implement docker at work leaving to time to play at home.

**Comment by edannenberg** [comment]
> I think the lib64 -> lib symlink should belong to build-root.sh. Any reason is not there?. I am thinking about it for musl support.

Usually the `glibc` install creates the symlink, unless there is already a `lib` dir, which in this case happens due to `gentoo-functions` package. Not sure how musl handles this. So for now I left it there.

> What is the relevance of this? I see the namespace hard-coded there. What if I use a different namespace name? I will be losing something?

The glibc image [switches](https://github.com/edannenberg/gentoo-bb/blob/kubler/dock/kubler/images/glibc/build.conf#L2) from `bob-musl-busybox` build container to `bob`. As a consequence `PACKAGES.md` information from the previous busybox build is lost, as it only exists in `bob-musl-busybox`. So we just recreate the busybox part in the fresh `PACKAGES.md`. Could be safely omitted otherwise.

**Comment by azimut** [comment]
I see, I never noticed the break on the build chain before. The more you know.

For what I saw trying to build x86_64 images with musl with this project and what I see on the official alpine docker images is that there's no use of lib64. On gentoo it looks like the lib dir is stored at the LIBDIR_${ARCH} var on the profile. So for glibc x86_64:
```
# grep LIBDIR /usr/portage/profiles/arch/amd64/make.defaults 
LIBDIR_amd64="lib64"
LIBDIR_x86="lib32"
LIBDIR_x32="libx32"
```

And for musl is:
```
/usr/portage/profiles/hardened/linux/musl/amd64/make.defaults:LIBDIR_amd64="lib"
/usr/portage/profiles/hardened/linux/musl/arm/make.defaults:LIBDIR_arm="lib"
/usr/portage/profiles/hardened/linux/musl/arm64/make.defaults:LIBDIR_arm64="lib"
/usr/portage/profiles/hardened/linux/musl/mips/make.defaults:LIBDIR_o32="lib"
/usr/portage/profiles/hardened/linux/musl/ppc/make.defaults:LIBDIR_ppc="lib"
/usr/portage/profiles/hardened/linux/musl/x86/make.defaults:LIBDIR_x86="lib"
```

This solves my conundrum. I will make a note to s/lib64/lib/ on build-root.sh for musl images regardless the arch. This might call for a better solution down the line. Will be acceptable somthing like call:
{code}
portageq envvar  LIBDIR_$(portageq envvar ARCH)
{code}
On build-root.sh to decide between lib and lib64 or is something that is better leave agnostic for this project?

**Comment by edannenberg** [comment]
> I see, I never noticed the break on the build chain before.

It's pretty much the only place such break occurs so most people probably never notice. 99.9% of the time it's also the wrong thing to do. :)

> portageq envvar  LIBDIR_$(portageq envvar ARCH)

Looks good to me, I'll take a closer look at this soonish.

**Comment by edannenberg** [comment]
Fixed with https://github.com/edannenberg/kubler/commit/b316b324b9047eab373163fb0a45f9c9066a1149. Thanks for bringing this up!
