### ISSUE TITLE
Portage update notification for packages

### ISSUE THREAD

**Issue by UralZima** [edannenberg/kubler#113]
Hi. I need update notification of new paclage versions.
Example. Portage got new version of PHP7.1.3, which contains security update. How would I know about that? In general gentoo use, I'll check emerge every day and see what upgraded. 
Using Kubler, no way to be notified about updated packages. When you manage multiple containers on production, security updates are important. I am already following some CVE-RSS feeds, but I would like to see such feature:

After building all packages and containers, kubler writes all versions of all packages into some file, per container. 
Then I issue some command, like 'kubler list-portage-updates', which syncs portage, and check each package from that list for new version. So output something like this:
kubler/nginx-php7
--- update available: php7.1.2 -> php7.1.3
kubler/mariadb 
--- update available: mariadb10.1.20->mariadb10.1.30

So it is just information to decide, if I need to update any of my containers. It seems easy to implement

**Comment by jbergstroem** [comment]
I can't help but feel that notification mechanisms are out of scope for kubler. In general gentoo use, you would probably follow GLSA's or `packages.gentoo.org` or any RSS that you would set up to track relevant packages.

**Comment by UralZima** [comment]
Why out of scope? Kubler is used to install nginx-php7 package, it knows which packages it installs. I need to manage updates/rebuilds somehow, keep system up to date. And need to know, when I need to rebuild the stack or concrete packages. All needed - write somewhere all emerged packages with versions, and then check this list with updated portage tree. if some lib is updated, I want also to know about that, like if libvpx is updated, I need to rebuild my ffmpeg package. 

Every day I do emerge --sync && emerge -DuvaN @world. with kubler, I don't know which updates are available.

**Comment by azimut** [comment]
You can grep Packages.md and diff with the latest portage (the regex of the atoms is something i dunno how to handle). So it can be a "tool" for kubler. Not the builder itself but it can live somewhere here mightbe.

**Comment by jbergstroem** [comment]
Just to elaborate; what i mean is this:
1. yes, it's kublers task to update the containers
2. no, i don't believe its kulbers task to either notify you or sync when packages needs to be updated

As @azimut mentioned; using the generated packages.md is probably the best way. `eix` is available in the builders as well, meaning the index should be super fast to query if you want to introduce this functionality into your builder.

**Comment by edannenberg** [comment]
Running `kubler update` already lists updated packages since the last sync, though I wouldn't recommend that for anything security related, instead:

> [gentoo-security](https://www.gentoo.org/support/security/) said:
>How to receive GLSAs
>
>GLSA announcements are sent to the gentoo-announce@gentoo.org mailing-list, and are published via RSS and Atom feeds.

So just subscribe to the mailing list or check the feeds.

**Comment by UralZima** [comment]
Thank you
