### ISSUE TITLE
Handle CTRL+C and do cleanup

### ISSUE THREAD

**Issue by UralZima** [edannenberg/kubler#116]
Hello. I often interrupt kubler, because I forgot something, see it doing wrong, forgot use flag and many other. I do ctrl+c, and many junk containers remain. 
What if kubler will trap ctrl+c and gracefully quit, removing intermediate and temporary containers?

**Comment by edannenberg** [comment]
This shouldn't happen anymore, provided you are using the latest version you should see a message `--> remove ${container_id}, NO_CLEANUP env prevents this` when you press `ctrl-c` during a build.

If you are on the latest version please provide some more details on cases where this still happens so I can reproduce the issue.

**Comment by edannenberg** [comment]
Any updates on this or can we close this?
