### ISSUE TITLE
Switching from spring to kubler issues

### ISSUE THREAD

**Issue by UralZima** [edannenberg/kubler#117]
Hello. I am switching from spring branch to newest kubler.
I have replaced all 'update_use' and 'update_keywords' to 'flaggie' to not modify any kubler scripts (for removing strict), so I can git pull.
I have copied my tmp folder for faster rebuilds. 

While building, I have bunch of messages, like: 
USE flags should not start with a '+': +make-symlinks
For busybox and other packages. Why this happens? I use flaggie on my host also and never got such messages. 

Also, while building glibc, I got:
 * 
 * Installation of a symlink is blocked by a directory:
 *   '/emerge-root/lib'
 * This symlink will be merged with a different name:
 *   '/emerge-root/lib.backup.0000'
 * 

5be34df2a38f / # ls -R lib
lib:
gentoo

lib/gentoo:
functions.sh

What this means? 

After adding/deleting overlay to layman in build.sh, I got

 * Warning: not able to parse config file: /emerge-root/etc/layman/layman.cfg
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/layman", line 46, in <module>
    main()
  File "/usr/lib64/python3.4/site-packages/layman/cli.py", line 155, in __call__
    " %s" % str(self.config.keys()), 6)
  File "/usr/lib64/python3.4/site-packages/layman/argsparser.py", line 419, in keys
    keys += [name for name, _ in self.config.items('MAIN')
  File "/usr/lib64/python3.4/configparser.py", line 835, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib64/python3.4/configparser.py", line 835, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib64/python3.4/configparser.py", line 832, in <lambda>
    section, option, d[option], d)
  File "/usr/lib64/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib64/python3.4/configparser.py", line 388, in _interpolate_some
    p = rest.find("%")
AttributeError: 'list' object has no attribute 'find'

**Comment by edannenberg** [comment]
> I have replaced all 'update_use' and 'update_keywords' to 'flaggie' to not modify any kubler scripts (for removing strict), so I can git pull.
>
> While building, I have bunch of messages, like:
USE flags should not start with a '+': +make-symlinks

The `ùpdate_use/keywords` helpers just pass it's args to flaggie with some extra options, so this should indeed just work. Did you double check the `build.sh` after your modifications? Maybe try the instructions in an interactive build container.

> Also, while building glibc, I got:
>
 >  Installation of a symlink is blocked by a directory:
    '/emerge-root/lib'
    This symlink will be merged with a different name:
    '/emerge-root/lib.backup.0000'

Looks like your glibc image is not up to date. The error is a side effect of not always installing the `baselayout` package before installing selected packages anymore. You have 2 options:

1. Handle any missing dirs/symlinks manually, like [glibc](https://github.com/edannenberg/kubler/blob/master/dock/kubler/images/glibc/build.sh#L29) does now.
2. Enable the old behaviour by setting `BOB_INSTALL_BASELAYOUT=true` in the image's `build.sh` or even for the namespace/globally.

>5be34df2a38f / # ls -R lib
lib:
gentoo
>
>lib/gentoo:
functions.sh
>
>What this means?

The `gentoo-functions` package is installed before `glibc`, unlike the glibc package it does not care if `lib/` is a symlink or not, so if `/emerge-root/lib/` does not exist yet the ebuild just creates the dir and calls it a day. `glibc` then prints the warning you got and instead creates `lib.backup.0000`. See above for the solution.

> After adding/deleting overlay to layman in build.sh, I got: ...
> Warning: not able to parse config file: /emerge-root/etc/layman/layman.cfg

I'm guessing you are adding the overlay in the `configure_rootfs_build` hook, keep in mind that `ROOT=/emerge-root` is active when this hook is executed. Apparently layman also respects this and tries to add the overlay in the wrong location. So layman overlays should always be added in the `configure_bob` hook. I'll add a note to the `build.sh` template.

Also, layman overlays are now stored in the new portage container volume, reasoning was deduplication (it's reused by all build containers) and update handling. As a side effect there is some wonky behaviour though when it comes to adding an overlay in a fresh build container which already was added previously in another build container.

Example for working around that can be seen in the [musl](https://github.com/edannenberg/kubler/blob/master/dock/kubler/builder/bob-musl/build.sh#L31) builder. There should probably be a helper for this, ideally wrapping layman transparently.

**Comment by UralZima** [comment]
Thanks. Flaggie issue was because you wrote 
update_use 'busybox' '+make-symlinks +static', which converted by function to flaggie +make-symlinks +static
when I replaced update_use to flaggie with sed, flaggie considered it as one argument. 

I have updated my glibc package and it seems built fine.

Layman issue was as you said, because I included it in configure_rootfs_build.

But one issue with layman remained. 
If image building failed which adds layman repo, on next rebuild emerge can't find a package in overlay. Solution is:
layman -d rindeal || true
layman -a rindeal || true
when just re-adding overlay, emerge finds the package.

**Comment by edannenberg** [comment]
Yea makes sense, the flaggie helpers currently allow for both formats.

Glad things worked out, I'll leave this open until I fixed the use flags, maybe remove all the single quotes for use flags, it's only good practice for package version atoms due to things like `>=some-package-1.2`.

**Comment by UralZima** [comment]
> Yea makes sense, the flaggie helpers currently allow for both formats.
I mean, flaggie accepts +static +make-symlinks and '+static' '+make-symlinks', not '+static +make-symlinks'. BTW, I saw you passing every flag as separate argument everywhere, only busybox and bob or glibc package have multiple flags in single quotes.

Please check the layman issue. It existed since you separated portage. If layman is added just in place, it is working, if build failed, layman is added, but portage don't see any packages from it on next rebuild. So only deleting and adding again helps.

**Comment by edannenberg** [comment]
You can now use `add_layman_overlay someoverlay` in your `configure_bob` hooks.

**Comment by berney** [comment]
This note is to help others trying to work out how to do things in Kubler.

> You can now use add_layman_overlay someoverlay in your configure_bob hooks.

I saw this, and then wondered how to add my own overlays rather than a well known one.
There is also an `add_overlay` helper: -

```
# Add Gentoo overlay to repos.conf/ and sync it
# Example usage: add_overlay musl https://anongit.gentoo.org/git/proj/musl.git
#
# Arguments:
#
# 1: repo_id - reference used in repos.conf
# 2: repo_url
# 3: repo_mode - optional, default: git
# 4: repo_priority - optional, default: 50
add_overlay()
```
