### ISSUE TITLE
Open a irc or slack channel?

### ISSUE THREAD

**Issue by edannenberg** [edannenberg/kubler#120]
Would there be any interest and what would you prefer?

Considering timezones my vote goes to slack.

**Comment by jbergstroem** [comment]
I would prefer IRC. Most open source gravitates to it; putting a slight more strain on handling your history but with things like bouncers (znc) and irccloud I feel its somewhat solved. We could additionally add irc logging.

**Comment by azimut** [comment]
I am not from the IRC generation (there is such thing?) but I like the unifying my IMs with IRC and bitlbee (I have an image build with this project too :P) 

Slack has the option to open IRC and XMPP "gateways". I think there is a history too (slackarchive?). No idea about pricing/implementation though.

**Comment by edannenberg** [comment]
I guess the issue tracker will do for now. :)

**Comment by r7l** [comment]
It would be nice to have a place to exchange some talk other then this issue tracker in here. There would also be Discord as an option, which is pretty much like Slack. Slack is expensive in the long run. I've left it due to lots of the project i was following, migrated over to Discord.

https://discordapp.com

**Comment by edannenberg** [comment]
Yea, it seems pretty popular these days. I have set up a server at https://discord.gg/rH9R7bc. Permissions are as broad as possible for now, no email verifcation required for discord accounts.

**Comment by r7l** [comment]
Great, i've joined. Maybe add it to the Github Readme.md to have it more visible.
