### ISSUE TITLE
oracle jdk and jre don't need to depend from GCC

### ISSUE THREAD

**Issue by azimut** [edannenberg/kubler#123]
only icedtea need it I think. As for the dependency of oracle-* packages, I think they only depend on glibc and bash. Haven't tested enough. Disclaimer: I barely use Java.

Edit: the depgraph make me realize of this

**Comment by edannenberg** [comment]
The JRE image never did, but you are probably right about JDK:

> [wikipedia](https://en.wikipedia.org/wiki/GNU_Compiler_for_Java) said:
The GNU Compiler for Java (GCJ) was a free compiler for the Java programming language and part of the GNU Compiler Collection.

Notice the past tense. This also suggests that `ìcedtea` only needs gcc at build time?

**Comment by edannenberg** [comment]
iced-tea seems to have a hard requirement on gcc. `kubler/jdk-openjdk` is also a thing now.
