### ISSUE TITLE
How to create a new builder

### ISSUE THREAD

**Issue by berney** [edannenberg/kubler#126]
I am trying to figure out how to create a new builder that is based off an existing builder. I want to make a musl-static builder that is just like the musl builder but it sets CFLAGS/LDFLAGS to have `-static`. 

I created a new namespace, `asdf`, and then a new builder and new image.

```
$ kubler new builder asdf/bob-musl-asdf

<enter> to accept default value

Extend an existing builder? Fully qualified image id (i.e. kubler/bob) if yes or else stage3
Parent Image (stage3): kubler/bob-musl

Successfully created asdf/builder/bob-musl-asdf builder at /home/berne/co/git/kubler/dock/asdf/builder/bob-musl-asdf

localhost:~/co/git/kubler$ kubler new image asdf/figlet

<enter> to accept default value

Extend an existing image? Fully qualified image id (i.e. kubler/busybox) if yes or scratch
Parent Image (scratch): kubler/busybox

Successfully created asdf/figlet image at /home/berne/co/git/kubler/dock/asdf/images/figlet
```

I edited `dock/asdf/images/figlet/build.conf`

```
# Used build container, optional, default: value of DEFAULT_BUILDER of namespace kubler.conf
BUILDER="asdf/bob-musl-asdf"

# Run build container in privileged mode, optional, default: false
#BUILD_PRIVILEGED=true

# Fully qualified image id (i.e. kubler/busybox), optional, default: scratch
IMAGE_PARENT="kubler/busybox"
```
Then I try to build it.

```
$ vi dock/asdf/images/figlet/build.conf
localhost:~/co/git/kubler$ kubler build asdf/figlet
*** generate build order
--> required engines:    docker
--> required stage3:     stage3-amd64-musl-hardened
--> required builders:    kubler/bob-musl asdf/bob-musl-asdf
--> build sequence:      kubler/busybox asdf/figlet
*** gogo!
--> build image kubler/bob-musl
--> build image asdf/bob-musl-asdf
--> phase 1: building root fs
using kubler/bob-musl:20170723
switching portage profile to: /var/sync//var/sync/portage/profiles/hardened/linux/musl/amd64


!!! /etc/portage/make.profile is not a symlink and will probably prevent most merges.
!!! It should point into a profile within /var/sync/portage/profiles/
!!! (You can safely ignore this message when syncing. It's harmless.)


!!! Your current profile is invalid. If you have just changed your profile
!!! configuration, you should revert back to the previous configuration.
!!! Allowed actions are limited to --help, --info, --search, --sync, and
!!! --version.
fatal: Failed to run image kubler/bob-musl:20170723
--> remove asdf-bob-musl-asdf-30048-14825, NO_CLEANUP env prevents this
```

I'm not sure if it is something simple like me referencing things incorrectly. I tried to find examples but all the builders I found are using stages instead.

Is there a simpler way to set CFLAGS and LDFLAGS for a specific package? Before the gentoo-bb spring rewrite I did something like this: -

https://github.com/berney/gentoo-bb-images/blob/master/images/figlet-musl-static/build.sh

```bash
CFLAGS="$(emerge --info|grep ^CFLAGS|grep -oP '(?<=").*(?=")') -static" \
	CXXFLAGS=$CFLAGS \
	LDFLAGS="$(emerge --info|grep LDFLAGS|grep -oP '(?<=").*(?=")') -static" \
	"${EMERGE_BIN}" ${EMERGE_OPT} --binpkg-respect-use=y --usepkg-exclude="$PACKAGES_M" -v $PACKAGES_M
```

Now I am trying to do something similar but in a less hackish and more proper way.

**Comment by edannenberg** [comment]
> !!! Your current profile is invalid.

The template for a new builder currently assumes a new stage3 builder, try removing all the default code in `configure_bob` hook of the new builder. The parent builder already took care of all that. I can see how this can be confusing though, will give this some more thought on how to improve.

To set custom CFLAGS for the new build container add an `ENV` command to the `Dockerfile.template` of your builder:

    ENV DEF_CFLAGS --mtune=generic -O4 -pipes

Why `DEF_CFLAGS`? See [portage-defaults.sh](https://github.com/edannenberg/kubler/blob/master/lib/bob-core/etc/profile.d/portage-defaults.sh) and [bob-core/Dockerfile.template](https://github.com/edannenberg/kubler/blob/master/lib/bob-core/Dockerfile.template). This is to ensure that those flags are only set once during build time of the build container and for example not overriden by different global/namespace variables on later runs.

> Is there a simpler way to set CFLAGS and LDFLAGS for a specific package?

For a single specific package a new builder seems overkill. I would probably just throw an `export CLFAGS=foo` into the image's build.sh. Won't get any simpler then that I think.

**Comment by berney** [comment]
Thanks for the help @edannenberg. I see I need to fix the `build.sh`, I'll try that and then edit here when done.

What are you thoughts on using the GitHub wiki feature to help document things? I'm tempted to start creating pages.

>> Is there a simpler way to set CFLAGS and LDFLAGS for a specific package?

> For a single specific package a new builder seems overkill. I would probably just throw an export CLFAGS=foo into the image's build.sh. Won't get any simpler then that I think.

I found that setting `-static` is causing lots of problems. I am now trying to be more targeted by specifying it for a particular atom. I am using the `/etc/portage/env/category/package` style I found here https://forums.gentoo.org/viewtopic-t-499881.html. I'm still working through problems with it thought, I think I may need to override the emerge process via https://wiki.gentoo.org/wiki/Handbook:AMD64/Portage/Advanced#Hooking_in_the_emerge_process so that I can change what's happening in the `./configure` script to make static compiling work. Otherwise I think I'll need to add an ebuild that supports a `static` USE flag and does what's needed.

**Comment by edannenberg** [comment]
> What are you thoughts on using the GitHub wiki feature to help document things? I'm tempted to start creating pages.

Any help for better documentation would be most welcome. Let me know if I need to configure anything else but public wiki should be enabled. I still have the documentation rewrite in my backlog but truth be told I burned myself out a bit earlier this year. Pretty much in maintenance mode the past couple of months. That being said feel free to poke for anything unclear, happy to help.

> I'm still working through problems with it thought, I think I may need to override the emerge process via https://wiki.gentoo.org/wiki/Handbook:AMD64/Portage/Advanced#Hooking_in_the_emerge_process so that I can change what's happening in the ./configure script to make static compiling work. Otherwise I think I'll need to add an ebuild that supports a static USE flag and does what's needed.

What kind of problems? `/etc/portage/env/category/package` approach should be pretty good for your use case I think. You can also try `EXTRA_ECONF` to add `./configure` options:

    EXTRA_ECONF ="--enable-foo ......" emerge package

Not sure how much of a hassle it is, but creating upstream patches for any missing `static` use flags might be the best long term solution as you don't have to maintain the ebuild.

> Also I think emerging to the builders root to get the dependencies built and then emerging to the /emerge-root/ with the static override might help. Most of the libs should be needed in the emerge root if the package I want is statically compiled. I need to keep investigating.

I'm still contemplating on or if this should be default, the impact on build time is quite high, even if binary packages are used for the second run.

**Comment by berney** [comment]
Great I'll start adding Wiki Pages. I thought I could create a page, but I wanted to check on your thoughts first.

Kubler is awesome, take a well deserved rest, and you can be proud of your work.

I'll keep ECONF in mind. I got it to work with the env override method, and then refactored to use an overlay anyway so that I can take advantage of proper binary packages. Portage only tracks USE flags and dependencies, but not CFLAGS etc. I push both methods to my ricer images repo (different branches) as I find it useful to look at the techniques and methods.

I will try to upstream my ebuilds as they are just adding static USE flag for now.

**Comment by azimut** [comment]
> I'm still contemplating on or if this should be default, the impact on build time is quite high, even if binary packages are used for the second run.

I am using something like this on some configure_bob() due some known bugs on some ebuilds (ex: https://bugs.gentoo.org/show_bug.cgi?id=611030):
```
emerge -j15 -vK ${_packages} || emerge -v ${_packages}
```
So it will try to emerge it from binaries in parallel first otherwise it will compile it.

Other related thoughts are:
- Add similar logic on emerge on ROOT
- Use `--with-bdeps=y --deep` on the emerge above as sometimes I think things are missed on subsequent runs when using binaries, which might be an issue on builds with a couple of layers.

**Comment by edannenberg** [comment]
> Great I'll start adding Wiki Pages.

👍 As I said, let me know if there are any things that need clarification.

> Kubler is awesome, take a well deserved rest, and you can be proud of your work.

Oh stop it. (don't) 😊 

> I'll keep ECONF in mind. I got it to work with the env override method, and then refactored to use an overlay anyway so that I can take advantage of proper binary packages. Portage only tracks USE flags and dependencies, but not CFLAGS etc.

Yea that's a good point.

@azimut, Yep, something along those lines was already outlined in #110. More often then not a few packages are updated between rebuilds though and you end up installing the whole thing twice. For smaller images this probably won't matter much, but on the other hand it isn't needed most of the time in the first place for those. It's usually the heavy images like php where you need this workaround and the impact on build time is pretty high.

Another consideration is that you end up with inconsistent builders, as sometimes packages are installed in the builder's `/` and sometimes not. Some child images might expect those packages at build time. Following that line of thought the most correct way would be to always install packages at the builder `/` first. It would eliminate all errors related to "buggy" ebuilds not handling a custom `ROOT` correctly and prevent reinstalls in child images, but the trade off is build time.

Maybe it should be configurable per namespace with possible per image overrides.

**Comment by edannenberg** [comment]
Documented now.
