### ISSUE TITLE
How to do interactive builder build

### ISSUE THREAD

**Issue by berney** [edannenberg/kubler#129]
I'm having problems building `kubler/bob-musl` after doing an `kubler update`. How can I do an interactive build of a builder image?

Looking at the source I saw a `--source-mode` but I can't get it to work.

**Comment by edannenberg** [comment]
I'm afraid currently not possible, as is `build -i` just looks for an image (not a builder) and starts the build container of the parent image. Sounds like a handy feature though, gonna take a closer look at this. Should be fairly straight forward. Maybe targeting a builder directly could also be solved in the same swoop, no promises on that front though. :P

> Looking at the source I saw a --source-mode

I had to look up that one before it rang a bell :), it's only for internal usage and runs inside the build container, it's used to handle some things differently in `build-root.sh`, depending on the build being interactive or not. (like for example not exiting the container on build errors, etc)

**Comment by berney** [comment]
OK. I look forward to the enhancement.

I'm away from my machine so I can't get the exact errors but I'll update this with them when I can. The error I'm getting in bob-musl is related to openssl USE bindist. If I update_use that in build.sh, it then gets a keyword error, if I update that it then gets a problem with openssh. If I unprep openssh it continues gets a different error.

**Comment by edannenberg** [comment]
Yep, same for glibc container. ´dev-python/cryptography-2.0.2´ update seems to be the culprit.
Try `emerge -C net-misc/openssh` before updating the use flag, seems to do the trick. Gonna push a fix later today.

**Comment by edannenberg** [comment]
Targeting a builder for interactive builds should work now. After some consideration I probably won't add targeting builders for regular builds as it only seems useful for exploring/debugging purposes.

**Comment by berney** [comment]
Works great. Thanks for this, it will make troubleshooting the builders if they break after upgrades much easier (and quicker).
