### ISSUE TITLE
Error when building image in different working directory

### ISSUE THREAD

**Issue by seifertm** [edannenberg/kubler#131]
I was not able to build an image outside of the kubler root directory. After setting up a (single) namespace, a builder, and an image, the build command fails.

Steps to reproduce (tested with a03e77bbd40be173ed3b2f73bdaca1d7ff39d737)
```
cd /tmp
git clone https://github.com/edannenberg/kubler.git
mkdir myproject
cd kubler/
./kubler.sh --working-dir=/tmp/myproject new namespace test
<create a single namespace, all other values left at the default>
./kubler.sh --working-dir=/tmp/myproject new builder test/bob
…
./kubler.sh --working-dir=/tmp/myproject new image test/myimage
…
./kubler.sh --working-dir=/tmp/myproject build test/myimage
fatal: Couldn't find kubler.conf in current or parent directories starting from /tmp/myproject
               Either cd to Kubler's project root or cd-into/create an external namespace dir.
```

**Comment by edannenberg** [comment]
When you run `./kubler.sh --working-dir=/tmp/myproject new namespace test` a new directory named `test` is created at `--working-dir` for the new namespace, which should be used as `--working-dir` for the following commands:

```
./kubler.sh --working-dir=/tmp new namespace myproject
...
./kubler.sh --working-dir=/tmp/myproject new image myimage
...
./kubler.sh --working-dir=/tmp/myproject build myimage
```

However there also seems to be a bug when using a single namespace, `./kubler.sh --working-dir=/tmp/myproject new builder test/bob` should have already failed in your example as `/tmp/myproject` is not a namespace dir. Gonna take a closer at look this weekend, thanks for reporting!

**Comment by edannenberg** [comment]
Issue should be fixed now, some missing checks regarding simple namespace handling. Let me know if there are any other problems.

**Comment by seifertm** [comment]
Creating a namespace works now, thanks.
Building the image or namespace does not, however:
```
$ ./kubler.sh --working-dir=/tmp/kubler new namespace myns
… (use defaults)
$ ./kubler.sh --working-dir=/tmp/kubler new image myns/img
… (use defaults)
$ ./kubler.sh --working-dir=/tmp/kubler build myns
fatal: Couldn't find kubler.conf in current or parent directories starting from /tmp/kubler
               Either cd to Kubler's project root or cd-into/create an external namespace dir.
```
Instead of building the namespace, I also tried building a single image:
```
$ ./kubler.sh --working-dir=/tmp/kubler/myns build img     
*** generate build order
fatal: Unknown namespace "kubler" for builder kubler/bob, expected "myns"
```

Should I open a new issue for this?

**Comment by edannenberg** [comment]
There are two parts to this issue:

>fatal: Couldn't find kubler.conf in current or parent directories starting from /tmp/kubler
               Either cd to Kubler's project root or cd-into/create an external namespace dir.

Kubler can't find a valid namespace dir to work with and quits, this should maybe more explicit. The error itself is ok though as `--working-dir` in your example should point to `/tmp/kubler/myns`:

```
$ ./kubler.sh --working-dir=/tmp/kubler new namespace myns
… (use defaults)
$ ./kubler.sh --working-dir=/tmp/kubler/myns new image myns/img
… (use defaults)
$ ./kubler.sh --working-dir=/tmp/kubler/myns build myns
```

The first command creates a new `multi` namespace `myns` at `/tmp/kubler`, the actual namespace dir with the images is created at `/tmp/kubler/myns/myns`, you could add then other namespaces to `/tmp/kubler/myns/`. You can rename/mv the top level `/tmp/kubler/myns` dir to something less confusing at any point, i.e. `kubler-workspace` or just use a `single` namespace if a single dir with all your images suffices.

So your example should have failed at the second command already as the working dir was not a valid Kubler namespace dir. Should be fixed now, see commit msg for details. I'll leave this open until I updated the docs regarding multi/single namespace handling.

**Comment by edannenberg** [comment]
Covered by the docs now.
