### ISSUE TITLE
Hardcode python3 slot

### ISSUE THREAD

**Issue by azimut** [edannenberg/kubler#135]
I see python 3.5/6 on stable keywords. I think it should be hardcoded on the build.sh.

**Comment by edannenberg** [comment]
The default is now `PYTHON_TARGETS="python2_7 python3_5"`, I'm guessing you mean the python3  image should be updated to use `python3_5`? If not, can you give me a bit more details on what exactly you would like to hard-code and why? Thanks!

**Comment by azimut** [comment]
Yes, on the python3 image. I was thinking on _packages on build.sh
```
_packages="dev-lang/python:3.4"
```
That or 3.5. I somehow got installed 3.6 on rebuild which was unexpected.

**Comment by edannenberg** [comment]
Ah yes I see, gonna update to `python3_5` as it is default now. Not sure why Portage also pulls in 3.6 though as it is not set in `PYTHON_TARGETS`.

**Comment by edannenberg** [comment]
Updated to 3.5, as per your suggestion 3.6 is no longer pulled in. Thanks for pointing that out, missed that one last month! 😊
