### ISSUE TITLE
add warning or change logic for passwd copy

### ISSUE THREAD

**Issue by azimut** [edannenberg/kubler#140]
Currently if _packages variable is empty the etc/passwd,groups will not be copy from the builder to the image.

There are valid use cases to not have _packages but want to have a default non-root user added. Like adding a glibc pre-compiled go binary to a minimal glibc image. 

Might be a warning can be added somewhere if _packages is empty or might be just a note somewhere or check before and after build.sh for the image runs and copy those files consequently if changed.

A helper function to add a user is something I have been thinking too, but not sure if it is that useful.

**Comment by edannenberg** [comment]
Agreed, actually ran into this myself before, easy to workaround but not exactly intuitive. The build now always copies `passwd/group` if the modification date changed during the build.

**Comment by azimut** [comment]
Cool, thanks for the fix!. I should remember too not add it on finish_rootfs_build() though.
