### ISSUE TITLE
kubler/bob-musl: USE changes are necessary to proceed

### ISSUE THREAD

**Issue by maljaberi** [edannenberg/kubler#143]
Trying to follow steps in the 'Quick Start' chapter:
`$ ./kubler.sh build kubler/glibc`

Build process fails with following message:

    The following USE changes are necessary to proceed:
    (see "package.use" in the portage(5) man page for more details)
    # required by dev-vcs/git-2.16.1::gentoo[pcre-jit,pcre]
    # required by app-portage/layman-2.4.2::gentoo[git]
    # required by app-portage/layman (argument)
    >=dev-libs/libpcre2-10.30 jit
    
    Use --autounmask-write to write changes to config files (honoring
    CONFIG_PROTECT). Carefully examine the list of proposed changes,
    paying special attention to mask or keyword changes that may expose
    experimental or unstable packages.
    fatal: Failed to run image kubler/bob-musl-core:20180227
    --> remove kubler-bob-musl-20550-7607, NO_CLEANUP env prevents this

Produced on commit 834750f2

Workaround:
    
    diff --git a/dock/kubler/builder/bob-musl/build.sh b/dock/kubler/builder/bob-musl/build.sh
    index 1af0a6e..3381b4e 100644
    --- a/dock/kubler/builder/bob-musl/build.sh
    +++ b/dock/kubler/builder/bob-musl/build.sh
    @@ -36,6 +36,7 @@ configure_bob() {
         # install default packages
         # when using overlay1 docker storage the created hard link will trigger an error during openssh uninstall
         [[ -f /usr/"${_LIB}"/misc/ssh-keysign ]] && rm /usr/"${_LIB}"/misc/ssh-keysign
    +    update_use '>=dev-libs/libpcre2-10.30' +jit
         emerge -C net-misc/openssh
         update_use 'dev-libs/openssl' -bindist
         update_use 'dev-vcs/git' '-perl''

Is the problem a bug in my system or a bug in kubler? Running Gentoo.

Thnx!

**Comment by edannenberg** [comment]
Thank you for reporting! This was a fail on my part, also had to set that `use` flag at one point but assumed the issue is resolved when I retried without it. Apparently Portage doesn't run the same checks when binary packages are involved. After deleting the binary packages I could reproduce this again. Fixed.
