### ISSUE TITLE
0.9.0 beta

### ISSUE THREAD

**Issue by edannenberg** [edannenberg/kubler#154]
This is a fairly large refactor that focussed mainly on QoL improvements, it also adds a few features that piled up over the last year but never got quite finished.

Highlights:

* Kubler is now ready for installation as a system app, ebuild is avail. at https://github.com/edannenberg/kubler-overlay
* Example images moved to separate repo at https://github.com/edannenberg/kubler-images
* Bash completion for all Kubler commands! Please let me know if you run into any edge cases or missing completions.
* An all new compact output mode that only displays Kubler messages while logging the rest to file logs
* Docker `HEALTH-CHECK` and custom image tests are now part of the build (create a new image from template to see examples for both)
* New `dep-graph` command to visualize image dependencies as png, ascii or raw dot
* `clean` command can now remove image(s) built by current namespace
* portage container is no longer updated via git, the amount of upstream changes makes it not worth it. the old behaviour is still supported though.

See commit message for a (mostly) complete changelog.

---

### Migration for previous users

1. Remove the old `kubler.sh` from your path, verify it's  not available any more before proceeding with the install of the new version
2. Check `README.md` of https://github.com/edannenberg/kubler/tree/0.9.0 branch for updated installation instructions

All runtime data now lives at `KUBLER_DATA_DIR`, default: `~/.kubler/`. If you want to keep your old binary cache and distfiles folder:

    sudo mv /path/to/old/kubler/tmp/{distfiles,downloads,packages} ~/.kubler/

The example images are pulled by Kubler from github to `~/.kubler/namespaces` and can be referenced from any namespace.

### TODO

* finish new docs, currently incomplete
* resolve a few cases where docker specific logic leaked into command scripts

---

Please give it a try and let me know if you run into any issues.

**Comment by r7l** [comment]
This is great. It's pretty late right now but i am going to install this version first thing tomorrow.

**Comment by r7l** [comment]
I've just added the repository and tried to installed Kubler. 

First of all, i would suggest to set the kubler-9999 to unstable. I wouldn't know any other 9999 Ebuild that would be considered stable.

But the Ebuild fails for me in general with this error:

```
>>> Emerging (1 of 1) app-emulation/kubler-9999::kubler
!!! Fetched file: kubler-2019012611.tar.gz VERIFY FAILED!
!!! Reason: Insufficient data for checksum verification
!!! Got:
!!! Expected: BLAKE2B BLAKE2S MD5 RMD160 SHA1 SHA256 SHA3_256 SHA3_512 SHA512 WHIRLPOOL
 * Fetch failed for 'app-emulation/kubler-9999', Log file:
 *  '/var/tmp/portage/app-emulation/kubler-9999/temp/build.log.gz'
```

I've made an Ebuild myself from yours: https://github.com/r7l/gentoo-overlay/blob/master/app-emulation/kubler/kubler-0.9.0.ebuild

Probably not perfect but it installed and works nice so far. Gonna run some more tests later today.

**Comment by edannenberg** [comment]
> First of all, i would suggest to set the kubler-9999 to unstable. I wouldn't know any other 9999 Ebuild that would be considered stable.

Yea, I forgot to mention that yesterday, this is only temporary. When the 0.9.0 branch is merged with master and first release is tagged, 9999 will be marked as unstable and I'll add a proper ebuild for the version.

> But the Ebuild fails for me in general with this error..

Oops, turns out using `vcs-snapshot` is not a good idea when pulling `HEAD` snapshots, the checksum will fail as soon as changes are pushed after the ebuild's manifest was created. I reverted back to a full clone for the 9999 version which should circumvent the issue.

Also fixed a minor issue with bash completion if the user command dir existed but didn't have any scripts.

**Comment by r7l** [comment]
The error seems to be on my end. I was under the impression that this _/etc/kubler.conf_, would allow me to put everything kubler does into one place, without any additional options. I've just checked the code and it seems like as if you need to add a `--working-dir` to every command. This wasn't an issue for me prior because i was working inside the Kubler directory, that was created with the _git pull_ command.

This should probably rather be a new feature request then.

**Comment by r7l** [comment]
I've tried to get Kubler working with the `--working-dir` option. As i said before, i've not used this option before but instead worked inside the Kubler directory.

When using this option without having KUBLER_WORKING_DIR defined anywhere i can't get Kubler to work at all. This `--working-dir` option does not really work as i would expect it to do.

Here is what i am doing:

1. `sudo kubler --working-dir=/var/lib/kubler new namespace r7l`
    - This creates a new namespace directory (called it /var/lib/kubler/images) and adds a directory for my namespace in it.
2. `sudo kubler --working-dir /var/lib/kubler/images new image r7l/nginx`
   - This creates a new image directory within my namespace
3. `sudo kubler --working-dir /var/lib/kubler/images build r7l/nginx`
   - This throws an error: `fatal: Couldn't read namespace conf /var/lib/kubler/kubler.conf`

There is in fact no file there. It has never been created in the original working directory. I don't really understand the concept of this. Wouldn't it be a better option to simply use a general working directory which you can set in /etc/kubler.conf and set a `$KUBLER_WORKING_DIR/images` or `$KUBLER_WORKING_DIR/namespaces`.

Another option might be to allow a KUBLER_NAMESPACE_DIR and place all namespaces there.

Not sure if i am thinking wrong here. The option for working-dir namespace directories are not really clear to me. The whole idea to use multiple different --working-dir options is kinda confusing.

**Comment by edannenberg** [comment]
> Wouldn't this allow me to set this KUBLER_WORKING_DIR="/var/lib/kubler" to /etc/kubler.conf?
>
> I've tried it and when testing, it is actually used there but is replaced somewhere else later. Is this a bug or feature?

Looked into the issue a bit, the var works, however currently it has to be an active ENV already before kubler is started, as the various `kubler.conf` files are read after the current working dir is determined. So a bit of chicken/egg problem. I'll give this some more thought.

> sudo kubler --working-dir=/var/lib/kubler new namespace r7l
> This creates a new namespace directory (called it /var/lib/kubler/images) and adds a directory for my namespace in it.

Assuming you have `KUBLER_DATA_DIR=/var/lib/kubler` this looks like a bug, the command should have created the `r7l` namespace at `/var/lib/kubler/namespaces/r7l` in that case.
Fix should be up by tomorrow.

> I don't really understand the concept of this. Wouldn't it be a better option to simply use a general working directory which you can set in /etc/kubler.conf and set a $KUBLER_WORKING_DIR/images or $KUBLER_WORKING_DIR/namespaces.

In a sense `${KUBLER_DATA_DIR}/namespaces` is that dir, though it acts primarily as fallback for the current `--working-dir`. The basic idea here is to allow external namespace dirs to reference the `kubler` namespace images without having to pull a copy to each different namespace dir. You can also place your own namespace dirs there though, which should suit your desired workflow.

If you created `/var/lib/kubler` manually before running kubler this might be also be an issue as currently the initialization will only run if the dir does not exist. Gonna add another check for existing but empty dir, and an error/abort if the dir doesn't look like a valid `KUBLER_DATA_DIR` and is not empty.

A workflow like you described should def. be supported, in fact it's how I use kubler myself, though I do have docker permissions for my non-root user on my desktop and always work from inside a namespace dir.

**Comment by r7l** [comment]
Thanks for your response. What i actually did after installing Kubler with Portage was editing `/etc/kubler.conf` and changed the following visible values:

```
# Kubler's runtime data dir, needs to be writable by the current user
KUBLER_DATA_DIR="/var/lib/kubler/data"
# Gentoo's stage3 and portage files download location
KUBLER_DOWNLOAD_DIR="/var/lib/kubler/downloads"
# Gentoo's build related downloads, like source code, patches, etc
KUBLER_DISTFILES_DIR="/usr/portage/distfiles"
# Gentoo's binary package cache location
KUBLER_PACKAGES_DIR="/var/lib/kubler/packages"
```

As i wasn't aware of any automation, i've decided to create at least `/var/lib/kubler` and also added those additional directories, as it is set in the config file. From that on i've started with the commands i've pasted in earlier.

**Comment by r7l** [comment]
I've just updated Kubler using your fixed Ebuild and i've also deleted everything within `/var/lib/kubler`, except for the directory itself. I've also removed the `/etc/kubler.conf` file prior of reinstalling Kubler.

This is the only setting i have in `/etc/kubler.conf` now:

```
KUBLER_DATA_DIR="/var/lib/kubler"
```

There still seems to be a bug somewhere. After installing and adding this line to the config file, i try to set up a new namespace. This returns an error message for me and will only add 2 files into `/var/lib/kubler`:

- kubler.conf
- kubler.conf.tmp

The error message says this:

```
sed: -e expression #1, char 7: extra characters after command
```

When trying to head on with creating an image, it also fails with this error message:

```
fatal: /home/r7l is not a valid Kubler namespace dir
```

**Comment by edannenberg** [comment]
Apparently I last-minute refactored a var name via IDE but it missed a ref. :/ Fix is up, please empty the DATA_DIR again.

**Comment by erm67** [comment]
looks great, I hope to be able to test it very soon on arm64 .....  too bad I had just created all containers I needed with the old version .....

**Comment by edannenberg** [comment]
The 0.9.0 branch should be pretty stable now, besides installing/migrating there should be  practically no BC issues using your existing builders/images with the new version. Just haven't found the time to finish the docs yet, soon(tm).

I remember you having issues on arm64 with the stage3 downloads, this should work as expected now, also added a workaround for the wrong filenames in the upstream arm64 digests file. Let me know if you run into any other (arm64) issues.

**Comment by edannenberg** [comment]
Found and fixed a couple of issues during the monthly rebuild. Hopefully I'll  find some time to cut a release this weekend.

**Comment by erm67** [comment]
It works great, I only made a couple of changes .... It is just that I am a bit busy at work ATM and I still have to fix my docker setup (unrelated to kubler).
There is one thing I'd love to have:

BOB_LDFLAGS
and 
BOB_BUILDER_LDFLAGS

for lto, but still have not found the time to dig into the scripts to find where to hack that in :-)

**Comment by edannenberg** [comment]
No worries, fairly short on time myself so I know the feeling. :(

I only had a cursory look at lto but I think something like the following should do the trick:

1. Create a new builder:

```
    kubler new builder lto/bob
    --> Parent Image: kubler/bob
```

2. Setup lto as described in their docs in the new builder

`/etc/profile.d/portage-defaults.sh` in the builder might be of interest for you.

3. Set `DEFAULT_BUILDER="lto/bob"` in your namespace or global `kubler.conf`, if it's global the kubler example images will also be built with your custom builder.

The lto project sounds interesting though, might be worth including a switch for. Feel free to hop on https://discord.gg/rH9R7bc for a chat or open a new issue/PR with your findings.

**Comment by edannenberg** [comment]
It's finally out, thanks @r7l for all the testing and feedback. Appreciated!
