### ISSUE TITLE
PHP fails to build (eselect issue)

### ISSUE THREAD

**Issue by janoszen** [edannenberg/kubler#157]
Hello,

It seems `dev-lang/php` fails to build due to an error with eselect. I have traced this down on my own gentoo-based Docker experiment to the fact that eselect does not respect the `ROOT` variable for the PHP builder.

Not sure if this should be addressed as a Gentoo bug or a workaround should be applied to Kubler.

**Comment by r7l** [comment]
I can't confirm this. I have 4 different PHP based containers. 2 with PHP 5 and another 2 with PHP 7. It might also help to run `emerge php` in `configure_bob()`. I am doing this to prevent some errors as there is PHP installed in the build container then.

Can you post your build.sh?

**Comment by r7l** [comment]
You're having Discord? It's still very small but existing. You're free to join in there: https://discord.gg/rH9R7bc

**Comment by edannenberg** [comment]
@janoszen Yea, sadly not all Gentoo ebuilds respect a custom `ROOT` properly. Considering the feature is rarely used this is bound to happen I guess. Ideally this would be adressed in the upstream ebuild, but as @r7l mentioned there are ways to work around those issues fairly easily:

```
_packages="dev-lang/foo"

configure_bob()
{
    # move any use flag/keywords config from configure_rootfs_build() hook to 
    # reuse the resulting binary package
    emerge dev-lang/foo
}
```

This will basically install the package directly in the build container root first, resolving any issues related to ebuilds that don't fully support a custom `ROOT`. For minor issues you may also get a bit creative instead to avoid the created overhead, like [here](https://github.com/edannenberg/kubler-images/blob/master/images/graph-easy/build.sh#L21) for example.

Looks like EAPI 7 has introduced a few new [variables](https://devmanual.gentoo.org/ebuild-writing/variables/) that could be useful: `SYSROOT`, `ESYSROOT` and `BROOT`. If the php ebuild is already on EAPI 7 you could try playing with these in your `build.sh` for now, should get handled automagically by Kubler soon.

**Comment by janoszen** [comment]
Hey Erik,

Thanks for the feedback, that’s very valuable. FYI I will mention Kubler in
my talk at DevOps Pro Europe on Wednesday.

Janos

**Comment by edannenberg** [comment]
Thanks for the heads up, did a bit of house cleaning and finally cut the 0.9.0 release. The ebuild issue is documented now.
