### ISSUE TITLE
Misspelling target-id in kubler build results in confusing message

### ISSUE THREAD

**Issue by jscoggins-parasoft** [edannenberg/kubler#169]
Observed with kubler v0.9.3 installed via kubler-overlay. 

I am currently going through the tutorial in the README and I hit a confusing error message from a typo.
`
$ kubler build mytest/figlet -nF
/usr/share/kubler/cmd/build.sh: line 285: validate_image: command not found
/usr/share/kubler/cmd/build.sh: line 286: build_image_no_deps: command not found
`

I kept seeing this error over and over when I would try and build the image. It turns out that I am not
using mytest as the namespace but test0. When I fix the namespace it works. 

$ kubler build test0/figlet -nF 
»[✔]»[test0/figlet]» done.

EDIT: markdown does not recogize the second block for some reason :/

**Comment by edannenberg** [comment]
Thanks for reporting! That's not very helpful indeed and shall get improved. Let me know if you run into any other issues.
