### ISSUE TITLE
du illegal option  when build in MacOS

### ISSUE THREAD

**Issue by zonshy** [edannenberg/kubler#170]
> $ kubler build mytest/tool -i
»»»»»[init]» generate build graph for interactive build of mytest/tool
»»» required engines:    docker
»»» required stage3:     stage3-amd64-hardened+nomultilib
»»» required builders:   kubler/bob
»[✔]»[init]» done.
»[⠋]»[portage]» download portage snapshot [ n/a ]
du: illegal option -- -
»[⠙]»[portage]» download portage snapshot [ n/a ]
du: illegal option -- -
»[⠹]»[portage]» download portage snapshot [ n/a ]
du: illegal option -- -
»[⠸]»[portage]» download portage snapshot [ n/a ]

**Comment by edannenberg** [comment]
Thanks for reporting! Looks like `du` on MacOS does not support the special `--` argument. As a workaround you can try using the verbose mode `kubler -v build mytest/tool -i`. Fix should be up soon(tm). Please let me know if run into any other issues, been a while since Kubler was tested on Mac.

**Comment by edannenberg** [comment]
Turns out `du` on MacOS does not support `--max-depth`, only the shorthand `-d`. Please give it a try with current master, I'll cut a new release soon if there are no other issues.

**Comment by zonshy** [comment]
hi, @edannenberg I have update to master .
`kubler build mytest/tool -i` 
there are no other issues. 
Thanks! ;)
