### ISSUE TITLE
How to use custom stage3 in a new builder from scratch

### ISSUE THREAD

**Issue by shaumux** [edannenberg/kubler#177]
I'm trying to build a new builder and have a custom stage3 for that
This  is what i've put in the build.conf for the builder
```
STAGE3_BASE="stage3-amd64-musl-hardened+libressl"
STAGE3_DATE="20200330"
ARCH="-amd64"
ARCH_URL="http://127.0.0.1:8000/stage3-amd64-musl-hardened+libressl-20200330.tar.bz2"
```
After that when I try to do kubler update,  I get  

> »»»»»[kubler-images]» check git remote for updates
»[✔]»[kubler-images]» no updates.
»»»»»[stage3]» check all namespaces for new releases
»»»»»[stage3]»[kubler]»[bob]» up-to-date 20200325T214502Z - stage3-amd64-hardened+nomultilib
»»»»»[stage3]»[kubler]»[bob-musl]» up-to-date 20200204 - stage3-amd64-musl-hardened
»»»»»[stage3]»[kubler]»[bob-uclibc]» up-to-date 20200316 - stage3-amd64-uclibc-hardened
/usr/share/kubler/lib/core.sh: line 375: warning: command substitution: ignored null byte in input
»[✘]»[stage3]»[shaumux]»[ryzen-musl]» fatal: Couldn't find a stage3 file for http://127.0.0.1:8000/stage3-amd64-musl-hardened+libressl-20200330.tar.bz2

**Comment by edannenberg** [comment]
Hi,

try removing the leading dash for `ARCH`, also `ARCH_URL` should only contain the base url where the stage3 file can be found:

```
ARCH="amd64"
ARCH_URL="http://127.0.0.1:8000/"
```

Kubler will fetch all filenames at `ARCH_URL` and then tries to find a file that matches `STAGE3_BASE` via regex.

I should probably reword the error message a bit for clarity.

**Comment by shaumux** [comment]
Thanks, that did it
