### ISSUE TITLE
How does kubler decide on library dependencies

### ISSUE THREAD

**Issue by shaumux** [edannenberg/kubler#178]
How does kubler ascertain which libraries to include?
I'm trying to build a few containers which depend on libraries provided by gcc.
The final image seems not to contain libraries from gcc.
If I try to run i get errors as
```
Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/lib/libQt5Network.so.5)
Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/lib/libQt5Xml.so.5)
Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/lib/libQt5Core.so.5)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/lib/libQt5Core.so.5)
Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/lib/libdouble-conversion.so.3)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/lib/libdouble-conversion.so.3)
```
Is there a way to include the libraries in the image without including gcc in the _packages?

**Comment by babykart** [comment]
There is a core function that you can place in your namespace/image/build.sh

```
finish_rootfs_build()
{
    # Copy c++ libs, may be needed if you see errors regarding missing libstdc++
   copy_gcc_libs
...
}
```

**Comment by edannenberg** [comment]
> How does kubler ascertain which libraries to include?

Kubler just uses Portage to manage dependencies, which is fine for almost all cases. However `libstdc++` is a bit of a special case as it is part of the gcc package. Given the size it doesn't make sense to always include the gcc package in docker images, even just including the runtime libs doesn't make sense as only few packages need it and it would bloat the images by several mega bytes. As pointed out by @babykart  use the `copy_gcc_libs` helper in those cases. Looking at the docs this should be added to the common build pitfalls section.

For further details on the build process see the [docs](https://github.com/edannenberg/kubler#understanding-the-build-process) and make sure to read all the comments in the generated `build.sh` file of a new image.

**Comment by shaumux** [comment]
@babykart @edannenberg Thanks, that worked.
I feel kind of stupid missing that, since i turned the code upside down searching for some dependency resolution method.

@edannenberg I agree that it would make sense to include this in the common build pitfalls
