### ISSUE TITLE
Layman obsolete, should be replaced by eselect repository

### ISSUE THREAD

**Issue by r7l** [edannenberg/kubler#187]
Some recent dependency of Layman had a breaking update. Using Layman just returns the following error:

```
 * Fetching remote list...
 * XML DBHandler - ET.ParseError: mismatched tag: line 4912, column 4
 * XML DBHandler - ET.ParseError: mismatched tag: line 4912, column 4
 * DbBase; error, Failed to read database at "/var/lib/layman/cache_930c3ed4a5f89f74fd810585751a06e3.xml"
 * Hint: If you manually set db_type. Please reset it and let layman-updater
 * migrate it. Otherwise layman's database is not initialized, nor populated
 * with any existing data.
 * Run the following: "layman-updater -m <db_type>"
```
After digging a bit, it seems as if Layman is considered obsolete anyways and using `eselect repository enable NAME` is the way to go for now:

https://wiki.gentoo.org/wiki/Eselect/Repository

**Comment by r7l** [comment]
Looks like `add_overlay` is pretty much doing what `eselect repository` does as well. Might be a chance to merge `add_overlay` and `add_layman_overlay` and make use `eselect repository` for both? 
It would add Gento offical overlays and custom unofficial overlays both into `/var/db/repos` and also `/etc/portage/repos.conf` like you did with `add_overlay`.

**Comment by edannenberg** [comment]
Thanks for the heads up @r7l! Fix should be up tomorrow.

**Comment by edannenberg** [comment]
Removed `add_layman_overlay()` and `configure_layman()`, `add_overlay()` can be used now as a replacement. Syntax is the same as before, except for the `repo_priority` arg which, afaik, is not supported by `eselect repository`. Overlay location changed from `/var/lib/repos` to `/var/db/repos`.

```
Examples:

#  add repo that is listed in `eselect repository list`, repo_id and url seem to be identical to layman's
add_overlay musl 
# add custom git overlay repo
add_overlay my-id <git_repo_url>
# add overlay with custom type like rsync
add_overlay my-id <overlay_url> <overlay_type>
```

Note: After updating please run `kubler update` to fetch updated kubler image namespace. I'll probably cut the next Kubler release next week.

**Comment by r7l** [comment]
Thanks allot. I've just tested it and it works.

**Comment by r7l** [comment]
There might still be an issue with this. If you build an image once, it works perfectly but if you rebuild a single image which uses `add_overlay` it wil fail with this error:

```!!! Error: error: r7l: repository already enabled, in /var/db/repos/r7l```

I guess it would be a good idea to check if a repo is existing already.

**Comment by r7l** [comment]
I am currently testing it a bit further as i have a few images using official and custom overlays within build.sh.

**Comment by edannenberg** [comment]
Hmm the checked out repo in `/var/db/repos/` will persist as the path is a docker volume, however the actual overlay config in `/etc/portage/repos.conf/` will not persist so it shouldn't matter when rebuilding an image. Let me know how if you can replicate the issue. Probably will add a skip for already enabled overlays either way.

**Comment by r7l** [comment]
I am currently rebuilding my stack of images a few times. Each run takes quite a while as it is running on some slower machine and it already failed on the first run when adding your Kubler overlay in the base builder. If it fails again, i might have to edit the builders to skip a couple tasks and head into using `add_overlay` right away.

**Comment by r7l** [comment]
After playing around with this a bit more, it seems as if using `eselect repository` might cause a few headaches. It seems that having repos in `/var/db/repos/` but not listed in `/etc/portage/repos.conf/` will cause `eselect` to fail with an exit code as the repo exists but it will also fail with `emaint sync` as the repo might not be known.

It was definitelly a bit easier with Layman but maybe it might be a good idea to remove any existing repo and add it back, everytime the add_overlay is run. So you actually add it. Or maybe just add the missing part in `/etc/portage/repos.conf/`. But somehow i wonder, if `/etc/portage/repos.conf/` is not persistent, wouldn't that mean that any repo added to a bob builder, would not be around later on?

**Comment by r7l** [comment]
Nevermind the last question. I've did a couple reruns and already thought that any overlay directly added to the bob builders would stay. But even so, any additional overlay added to any other image would break if you rerun the build process.

I've added this for a test:

```
add_overlay() {
    local repo_id repo_url repo_mode
    repo_id="$1"
    repo_url="$2"
    repo_mode="${3:-git}"

    if [ -d "/var/db/repos/${repo_id}" ]; then
      if [ ! -f /etc/portage/repos.conf/eselect-repo.conf ] || ! grep -Fxq "${repo_id}" /etc/portage/repos.conf/eselect-repo.conf; then
        rm -R "/var/db/repos/${repo_id}"
      fi
    fi

    if [[ -z "${repo_url}" ]]; then
      eselect repository enable "${repo_id}"
    else
      eselect repository add "${repo_id}" "${repo_mode}" "${repo_url}"
    fi
    emaint sync -r "${repo_id}"
}
```

It does work but it should be polished.

**Comment by edannenberg** [comment]
After some further testing the only breaking case seems to happen when trying to `add` an already installed overlay (exit code 250), in my tests it didn't matter if the folder already existed as long as there was no config entry in `/etc/portage/repos.conf/`. I pushed a fix, please give it a try. (You can use an interactive build for testing to speed up the process a bit)

**Comment by r7l** [comment]
Thanks for adding it. I'll take a look as soon as i have the time. Hopefully the upcoming weekend.

**Comment by r7l** [comment]
Took longer then expected but i've did a few tests and had my entire stack of images rebuild with this new fix. I've also tried to add the same overlay in multiple images and so far it seems to be working as expected.

**Comment by edannenberg** [comment]
Thanks! No worries, not much time myself either. New release is out.
