### ISSUE TITLE
kubler build:  glib-2.64.5 is failing to install while building app-misc/mc image

### ISSUE THREAD

**Issue by TerraTech** [edannenberg/kubler#190]
I have started learning kubler and decided to try and containerize ```app-misc/mc```

During the build, ```dev-libs/glib-2.64.5``` keeps failing to install.

I've clipped out the relevant portion of the build:
```
* Messages for package dev-libs/glib-2.64.5 merged to /emerge-root/:

 * FAILED postinst: 1
 * ERROR: dev-libs/glib-2.64.5::gentoo failed (postinst phase):
 *   Update GIO modules cache failed (for amd64)
 *
 * Call stack:
 *     ebuild.sh, line  125:  Called pkg_postinst
 *   environment, line 3580:  Called multilib_foreach_abi 'multilib_pkg_postinst'
 *   environment, line 3241:  Called multibuild_foreach_variant '_multilib_multibuild_wrapper' 'multilib_pkg_postinst'
 *   environment, line 2880:  Called _multibuild_run '_multilib_multibuild_wrapper' 'multilib_pkg_postinst'
 *   environment, line 2878:  Called _multilib_multibuild_wrapper 'multilib_pkg_postinst'
 *   environment, line  655:  Called multilib_pkg_postinst
 *   environment, line 3578:  Called die
 * The specific snippet of code:
 *           gnome2_giomodule_cache_update || die "Update GIO modules cache failed (for ${ABI})"
 *
 * If you need support, post the output of `emerge --info '=dev-libs/glib-2.64.5::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/glib-2.64.5::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-libs/glib-2.64.5/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-libs/glib-2.64.5/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-libs/glib-2.64.5/homedir'
 * S: '/var/tmp/portage/dev-libs/glib-2.64.5/work/glib-2.64.5'

 * Messages for package app-misc/mc-4.8.25-r1 merged to /emerge-root/:

 * To enable exiting to latest working directory,
 * put this into your ~/.bashrc:
 * . /usr/libexec/mc/mc.sh

 * Messages for package dev-libs/libxml2-2.9.10-r4 merged to /emerge-root/:

 * Skipping XML catalog creation for stage building (bug #208887).

 * IMPORTANT: 3 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

»[✘]»[mytest/mc]» fatal: Failed to run image kubler/bob:20210210
»[✘]»[mytest/mc]» removing rootfs-builder-mytest-mc-31373-16729, NO_CLEANUP env prevents this
```

Is there something I've overlooked to accommodate for?

If you need further info/details/logs, please let me know.

**Comment by edannenberg** [comment]
> gnome2_giomodule_cache_update || die "Update GIO modules cache failed (for ${ABI})"

This is a bit of a flaw of Portage's `ROOT=` feature you will run into every now and then. The ebuild tries to execute `gnome2_giomodule_cache_update` during postinstall but the file only exists under `$_EMERGE_ROOT/` and not in the `PATH` of the build container. You could install the package first in the `configure_builder()` hook to get rid of the error, but that would likely execute `gnome2_giomodule_cache_update` in the wrong context. 

In this case you could fake the install of `gnome2_giomodule_cache_update` by creating a symlink to `true` in the `configure_rootfs_build()` hook to get past the error. Then run `gnome2_giomodule_cache_update` via `Dockerfile.template` to have it execute in the right context.

See [Common Build Pitfalls](https://github.com/edannenberg/kubler#common-build-pitfalls) section of the docs for more details.

**Comment by TerraTech** [comment]
Is this an example of how to fix it?
https://github.com/edannenberg/kubler-images/commit/65da086dd338c0f5d513fdfa1c02391d7ca9b0b3

**Comment by TerraTech** [comment]
Ok, I looked over how to accomplish the 2nd suggestion, but ran into an issue I'm not sure how to workaround.

The problem is that ```gnome2_giomodule_cache_update``` isn't an executable file, but rather provided as a function by the
```gnome2-utils.eclass``` inheritance.

How do I call an eclass function in the Dockerfile to execute it in the right context?

**Comment by edannenberg** [comment]
> How do I call an eclass function in the Dockerfile to execute it in the right context?

Probably not worth the effort, best to look at the eclass function and see whats happening inside. Looking at the fix you linked it will most likely call `gio-querymodules`. So no need for `Dockerfile.template` as you can pass the right context via `build.sh` already.

**Comment by TerraTech** [comment]
That is what I ended up doing.  Thank you for your help, I've got this squared away now.  I'm sure it will just take some time to fully wrap my brain around this amazing project as I'm still climbing the learning curve (started this morning).
