### ISSUE TITLE
What about Bob?

### ISSUE THREAD

**Issue by TerraTech** [edannenberg/kubler#191]
Now that I've made a lot of progress with climbing the Kubler learning curve, my ```docker images``` list has become a growing multiplicity of ```bob```.

Just out of curiosity, what does the ```bob``` naming mean?  Is it a person's name, an acronym or just simply ```bob```?  After working with Kubler enough, we know what the ```bob``` images represent, but not the actual name itself.

The closest I came to finding an answer was in #43, along with digging through the source looking for a clue.  Now that I've got that movie stuck in my head, I even searched for a random goldfish making baby steps with Bob to the elevator, but came up dry.  ;)

**Comment by edannenberg** [comment]
Yea primarily it is a reference to bob the builder(tm), I wanted to keep the prefix as short as possible yet somewhat meaningful. You may also see it as an acronym for builder of builds.

**Comment by TerraTech** [comment]
Aha - thank you for the insight, it is a spot-on naming prefix (_once you are in the know_).  ```:)```
