### ISSUE TITLE
Update fails for bob builder

### ISSUE THREAD

**Issue by r7l** [edannenberg/kubler#193]
Hello,

i am no longer able to update Kubler. For some reason, it won't show anything for my bob image. My custom builders are pretty much like yours. Just a few minor tweaks and i am using them for months now. I've also updated my build.conf to your latest changes.

```
»»»»»[stage3]»[base]»[bob-musl]» up-to-date 20210327 - stage3-amd64-musl-hardened
»[✘]»[stage3]»[base]»[bob]» fatal: Couldn't find a stage3 file for http://gentoo.mirrors.ovh.net/gentoo-distfiles/releases/amd64/autobuilds/current-stage3-amd64-hardened+nomultilib/
```

I am not certain how to approach this issue as i was skipping through `core.sh` but somehow i am not sure how you obtain the most recent version. Even more so, as there seem to be differences from mirror to mirror. I've tried most of the German mirrors and also mirror.gentoo.org but the issue remains the same.

Is there any mirror that should be prefered?

**Comment by edannenberg** [comment]
Hey,

yea I also ran into this today. Seems to be some kind of weird edge case as it works when using `build -v`. I'll try to look into this at the weekend.

**Comment by r7l** [comment]
Maybe it would be possible to add a new option (STAGE3_FILE?) to the builders `build.conf` where it is possible to add a direct link to a custom stage3 file that will skip the entire automated process and just pull and use this file.

The most possible use case i see for this, would be emergency situations like this, where the update process gets stuck for some reason.

**Comment by edannenberg** [comment]
I can't seem to reproduce this anymore. Could you try again on your end please? I'll think about passing a direct stage3 link.

**Comment by r7l** [comment]
I still have this issue using: `http://gentoo.mirrors.ovh.net/gentoo-distfiles` as mirror. But it works with other mirrors now.

**Comment by edannenberg** [comment]
Thanks. Looks like the issue is that some mirrors truncate the stage3 file name for display, which breaks the parsing. Switched to parsing the `a href` element instead, also handles possible url encoded `+` chars in the filename now.

**Comment by r7l** [comment]
Thanks allot. It's kinda hard to test for me right now as it currently works. But i guess it will be in the next version of Kubler and it's good to know there is a fix for it in already.
