### ISSUE TITLE
fatal: Couldn't find a image dir for kubler/bob

### ISSUE THREAD

**Issue by Alteroldis** [edannenberg/kubler#199]
I tried using the Kubler as described in README here, but i got this error, when executing the comman "kubler build my/student -i". Could this be due to the fact that I created a new namespace (my) in the same directory as the KUBLER_DATA_DIR one? It seemed to me that it sounds stupid, I didn't even check what would happen if I did it in another directory.
<details> 
  <summary><b>Tree of KUBLER_DATA_DIR</b></summary>

    ├── kubler.conf
    ├── log
    │   └── update.log
    ├── my
    │   ├── images
    │   │   └── student
    │   ├── kubler.conf
    │   └── README.md
    └── namespaces
        └── kubler
            ├── builder
            ├── images
            └── kubler.conf
</details>

1/ I run in KUBLER_DATA_DIR kubler new namespace my
2/ cd my; kubler update
3/ kubler new image student
4/ Few edit my student/build.sh file, add inside a configure_builder hook the add_overlay directive.
5/ kubler build my/student -i
And got output below:
»»»»»[init]» generate build graph for interactive build of my/student
»[✘]»[init]» fatal: Couldn't find a image dir for kubler/bob

**Comment by edannenberg** [comment]
Hi, can't say I ever tested this case. :) Try moving the `my` dir into the `namespaces` dir or run the `new namespace` command outside of the `KUBLER_DATA_DIR`.

**Comment by Alteroldis** [comment]
Hmm... both cases didn't work. Could this be due to the fact that I chose a single working dir type when creating a new namespace?

**Comment by edannenberg** [comment]
Shouldn't matter for both cases. Looking at the error message there seems to be a problem looking up the `kubler/bob` builder image. Are you using the default `KUBLER_DATA_DIR` at `~/.kubler/` or did you configure something else. If so, how?

**Comment by Alteroldis** [comment]
No, I defined other dir in /etc/kubler.conf before first run of kubler. But, for clearity, it dir (/home/foo/cephfs/kubler) is inside of /mnt/cephfs/foo, because /home/foo/cephfs is soft link to /mnt/cephfs/foo, that is mount point of my CEPH storage. However, the user, from whom I executed kubler, has all permissions in all dir in /mnt/cephfs/foo.

**Comment by edannenberg** [comment]
I see, maybe the symlink is the issue then. Could you try using the real path ` /mnt/cephfs/foo/kubler` in `/etc/kubler.conf` instead? If that also fails I would suggest to try the default location just to narrow down the problem.

**Comment by edannenberg** [comment]
Assuming this is resolved, feel free to reopen.
