### ISSUE TITLE
uClibc has been abandoned from Gentoo

### ISSUE THREAD

**Issue by r7l** [edannenberg/kubler#201]
When trying to update Kubler it fails since the Kubler default namespace (yours) contains a builder for uClibc. It tries to find an image that has been abandoned. It's a similar situation we've had recently with OpenRC / Systemd images but this time uClibc seems ti be gone for good. I've just asked in IRC.

```
»[✘]»[stage3]»[kubler]»[bob-uclibc]» fatal: Couldn't find a stage3 file for http://ftp.fi.muni.cz/pub/linux/gentoo/releases/amd64/autobuilds/current-stage3-amd64-uclibc-hardened/
```

**Comment by thesamesam** [comment]
Yeah, see https://www.gentoo.org/support/news-items/2021-08-18-uclibc-ng-retirement.html.

**Comment by r7l** [comment]
Just went through the `kubler.conf` file and figured there is an option to disable the Kubler namespace. Works perfectly again but the problem remains for everyone using the namespace.

**Comment by edannenberg** [comment]
Thanks for he heads up! Fix is up.
