### ISSUE TITLE
configure_eix is failing over missing example file

### ISSUE THREAD

**Issue by r7l** [edannenberg/kubler#203]
Kubler is currently failing with this error:

`cp: cannot stat '/etc/portage/repo.postsync.d/example': No such file or directory`

It comes from [this line](https://github.com/edannenberg/kubler/blob/master/engine/docker/bob-core/build-root.sh#L106) but i am not entirely sure where the example file should come from. I don't have it on any of my systems. It might have been part of the stage 3 tar file at some point.

I was searching Google a bit and found [this file](https://github.com/Sharrisii/TAZ/blob/master/TAZ_x86_v1_specs/catalyst/portage/repo.postsync.d/example). While i think, it should be the file in question, it's most likely not the package that was used by Kubler / Gentoo.

There might be an option to replace this egencache file (and maybe also [install_git_postsync_hooks](https://github.com/edannenberg/kubler/blob/master/engine/docker/bob-core/build-root.sh#L89)) with [this](https://github.com/vaeth/portage-postsyncd-mv) as it also contains an [egencache postsync hook](https://github.com/vaeth/portage-postsyncd-mv/blob/main/repo.postsync.d/50-egencache) and is written by the Eix developer.

**Comment by edannenberg** [comment]
As always thanks for the heads up! I'll try to to look into this by the end of the week.

**Comment by edannenberg** [comment]
Looks like the example got removed because `eix` provides some helper scripts now that simplify the process. Updated `configure_eix` accordingly.
