### ISSUE TITLE
Portage complaining about /run directory not being mounted

### ISSUE THREAD

**Issue by r7l** [edannenberg/kubler#204]
According to [this issue](https://bugs.gentoo.org/816303) in Gentoo, they've [added a check](https://github.com/gentoo/portage/blob/master/lib/_emerge/actions.py#L3023) for `/run` being a mounted directory instead of being a normal directory in the system. Looks like this does not work well with Docker (or at least Kubler) since `/run` is a normal directory there.

You'll get this warning message now for every build:
```!!! It seems /run is not mounted. Process management may malfunction.```

While it is already possible to use `BUILDER_DOCKER_ARGS_GLOBAL` and mount `/run` as tmpfs, i wonder if it might be possible to have a permanent solution and add it to the default volumes when building.

The other option might be a new issue in Gentoo bugtracker and ask them to not check if `/run` is mounted but instead just an existing directory.

**Comment by berney** [comment]
I added `BUILDER_DOCKER_ARGS_GLOBAL=('--tmpfs' '/run')` to my `kubler.conf` to get rid of this warning.

I agree that a permanent solution would be best, either having kubler use a tmpfs mount for `/run` to make the portage check happy, or getting upstream to relax their check. I opened PR #205 to for fix in kubler.

**Comment by r7l** [comment]
Ya, the better place to address this issue would be Portage. I don't see a real reason for `/run` being a tmpfs mounted directory. If there is a `/run` with proper permissions, it should be ok.

**Comment by berney** [comment]
@r7l As you saw in #205 this can probably be closed now that Portage reverted the change
