### ISSUE TITLE
Kubler expects a TTY, `kubler build` broken in CI/CD

### ISSUE THREAD

**Issue by berney** [edannenberg/kubler#212]
I'm working on getting Kubler running in a CI/CD (GitHub).

`kubler build` expects to have a working TTY, as the docker engine runs `docker run -it`, with the `-t` being `--tty`.

Due to this it's not possible to run it in GitHub Workflows (CI/CD), as the `docker run` command fails.

# Workaround

Making it not use `-t` works.

```patch
diff --git a/engine/docker.sh b/engine/docker.sh
index 252d1de..d5a7611 100644
--- a/engine/docker.sh
+++ b/engine/docker.sh
@@ -548,7 +548,7 @@ function run_image() {
         docker_mounts+=('-v' "${dmnt}")
     done
     # general docker args
-    docker_args=("-it" "--hostname" "${container_host_name//\//-}")
+    docker_args=("--hostname" "${container_host_name//\//-}")
     [[ "${auto_rm}" == "true" ]] && docker_args+=("--rm")
     [[ -n "${container_name}" ]] && docker_args+=("--name" "${container_name//\//-}")
     [[ "${BUILDER_CAPS_SYS_PTRACE}" == "true" ]] && docker_args+=('--cap-add' 'SYS_PTRACE')
```

# Goal Solution

It would be good to have `kubler` dynamically handle a TTY or not, or at least have a config variable that can be set to make it work without a TTY.

I believe some CI/CDs will handle ANSI escape codes (colors), despite not being a valid TTY. So it might be nice to force colours still. Ideally this would be configurable.

I haven't found time to write a PR for a proper solution yet.

# Notes about `tput`

It also gets warnings from `tput` when the `TERM` environment variable isn't set.

`tput: No value for $TERM and no -T specified`

In this case an unspecified terminal type is used (sounds like it's not well defined).

In GitHub workflows, `TERM=dumb` but isn't exported, so kubler doesn't have it.

In my experience these tput warnings can be ignored, but pedantically might want to detect a lack of a TERM and use some well defined behaviour. A user could just export a `TERM=SOMETHING` to get this.

**Comment by edannenberg** [comment]
Thanks for reporting! 

I added a fix for the TTY issue, should work automagically.

IIRC ANSI codes didn't play nice when redirecting output to a log file so these are removed right now when not on a terminal. Sadly I don't have the time right now to investigate this further.

`TERM` seems to be set to `dumb` by bash internally when not set by the environment, if set to `dumb` ANSI codes were ignored during my local tests. So it looks like we would need to set it to something else to get colors.

To get rid of the warning we could just `export TERM` before `tput` is used.

**Comment by berney** [comment]
Thanks for fixing this, I've tested it and it works.
