### ISSUE TITLE
Patches in acct-user.eclass failing due to recent changes

### ISSUE THREAD

**Issue by r7l** [edannenberg/kubler#218]
Seems like they've added some changes to `acct-user.eclass` again. This causes `0003-Revert-acct-user.eclass-Fixing-user-group-creation-w.patch` to fail and stop Kubler from working. It seems as if some of the code you've patched has been removed completely.

**Comment by r7l** [comment]
I've tried to look into this for a bit and figure if there might be a way around this. But i am not really experienced with all the side effects of $ROOT. Looking into the most recent commits, they've changed quite a bit of code including dependencies and even dropped some functionts. I would guess, patching eclass files back isn't going to work out well long term. Ebuilds will rely on current eclass files and causing more issues.

**Comment by r7l** [comment]
Maybe i am naive here but i've went through this with locally patching Kubler to not patch files in Portage and instead create a empty file at `${_EMERGE_ROOT}/etc/group` if there is non, in order to get past the issue of not having the file. The build process successfully went through after that and i don't have any issues (yet) with a number of different images. Even rebuilding with prebuild packages does work.

I've compared the final images with ones created with a older state of Portage with Kubler patches. I don't see anything different in `/etc/passwd` or `/etc/group` files.

I've not yet ran into any issue with `fowners` or anything as outlined in [209](https://github.com/edannenberg/kubler/issues/209).

**Comment by r7l** [comment]
Nevermind my last comment. I've tested more images and actually ran into multiple issues. And yes, `fowners` can hit issues as well.

**Comment by edannenberg** [comment]
I updated the patch `acct-user.eclass` and added a new one for `acct-group.eclass`. If you are still running into problems after updating Kubler please manually delete the respective binary packages.

**Comment by r7l** [comment]
Just wanted to say thank again. Your fix works perfektly. Did a rebuild of my entire stack and it went through as before.
