### ISSUE TITLE
User eclass patches broken again

### ISSUE THREAD

**Issue by r7l** [edannenberg/kubler#219]
Gentoo just deleted the `user.eclass` and with that, the patches are broken again. From what it looks like it they've just removed the file without touching the others. With that it shoud be enought to remove `0001-Revert-user.eclass-Fixing-user-group-creation-when-u.patch` file.

**Comment by edannenberg** [comment]
Thanks for reporting! Apparently `user.eclass` was deprecated for quite some time now in favor of [acct-user](https://devmanual.gentoo.org/eclass-reference/acct-user.eclass/index.html). Need to update your overlay if your ebuilds relied on it.

Fix is up.

**Comment by r7l** [comment]
Thanks allot. 

How about making a new release? If anyone is downloading the most recent release they will sit there with broken version. There are quite a number of important fixes since it was released.
