### ISSUE TITLE
Here we go again: user eclasses have been updated again and causing trouble for Kubler 

### ISSUE THREAD

**Issue by r7l** [edannenberg/kubler#222]
EAPI 6 was removed which would be trivial to patch but there have been a [couple more changes](https://github.com/gentoo/gentoo/commit/22e986ce87b4f983e9508803b83466c5183cde65).

**Comment by edannenberg** [comment]
Thanks for the report! Changes to these eclasses only affect Kubler if they clash with our patches. Hopefully get to fix it in the coming days, been out of order last week due to heavy flu.

**Comment by r7l** [comment]
That much i've figured. But there have been some changes to $ROOT variable handling in those commits. Take your time and most importantly get well soon.
