### ISSUE TITLE
Apptainer/Singularity support?

### ISSUE THREAD

**Issue by APN-Pucky** [edannenberg/kubler#223]
I am curious about the apptainer support? Or do you know that the conversion from docker to apptainer will work with the Dockerfiles from kubler?

I think it might be very interesting to have cpu tuned images for clusters. The HPC clusters often allow singularity and less often docker due to permissions.

**Comment by edannenberg** [comment]
Hi, I have no experience with Apptainer but looking at their [docs](https://apptainer.org/docs/user/main/docker_and_oci.html#) it looks like it will work reasonably well. The listed limitations are avoidable as you are building your own image stack anyways.

**Comment by APN-Pucky** [comment]
My first/initial tests all worked out well :+1:
