### ISSUE TITLE
error when calling app-portage/flaggie

### ISSUE THREAD

**Issue by dtuser007** [edannenberg/kubler#236]
I created an arm64 builder from scratch, changed the build.conf accordingly, build the builder successfully.
Then I created a new image. 

Now when running "kubler build -c <namespace>" I get the error 
  "flaggie: error: --strict: Argument not recognized as any type, pass e.g. use::-strict to force one"

The build fails fatal. Must be something in "kubler/engine/docker/bob-core/build-root.sh" but I don't understand, how to fix it. 

"flaggie --help" doesn't show any of the used options --strict or --destructive-cleanup.
Any ideas how to work around or fix this?

**Comment by dtuser007** [comment]
Thank you for prompt reply! I guess you mean the builer.sh of the builder. Here it is:
configure_builder() {
    fix_portage_profile_symlink
    eselect news read new 1> /dev/null
    emerge app-portage/flaggie app-portage/eix app-portage/gentoolkit
    configure_eix
    mkdir -p /etc/portage/package.{accept_keywords,unmask,mask,use}
    touch /etc/portage/package.accept_keywords/flaggie
    echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
    locale-gen
    echo 'LANG="en_US.utf8"' > /etc/env.d/02locale
    env-update
    source /etc/profile
    [[ -f /usr/"${_LIB}"/misc/ssh-keysign ]] && rm /usr/"${_LIB}"/misc/ssh-keysign
    emerge -C net-misc/openssh
    update_use 'net-misc/openssh' -bindist
    update_use 'dev-libs/openssl' -bindist
    emerge dev-libs/openssl
    update_use 'dev-vcs/git' '-perl'
    update_use 'app-crypt/pinentry' '+ncurses'
    update_keywords 'dev-python/ssl-fetch' '+~amd64'
    update_keywords 'app-admin/su-exec' '+~amd64'
    emerge dev-vcs/git app-eselect/eselect-repository app-misc/jq app-shells/bash-completion
    [[ "${BOB_UPDATE_WORLD}" == true ]] && emerge -vuND world
    add_overlay kubler https://github.com/edannenberg/kubler-overlay.git
    emerge dev-lang/go
}

In the builder.sh for the image I only added the package I wanted to try with "_packages="net-misc/asterisk"
Everything else left empty for future tuning.

I will try with the linked script.

**Comment by r7l** [comment]
>Thank you for prompt reply!

I was a little to quick i guess. Should have more carefully read your issue. Your build.sh looks fine. The issue actually is with Flaggie, which was updated. There was a [PR about it](https://github.com/edannenberg/kubler/pull/226) lately and it is in the most recent version of Kubler already.

Flaggie no longer has these options. The issue most likely is within the other image build.sh file. Can you share this one or at least the lines where you update use flags, keywords or masks?

**Comment by dtuser007** [comment]
Hmpf. I am running kubler from the gentoo kubler ebuild "https://github.com/edannenberg/kubler-overlay.git" and just unmerged and re-emerged it. The freshly installed function "update_use()" still has the issue acc. the linked PR, i.e. uses the deprecated options for flaggie
I will try to git clone manually and come back. Sorry for the noise.

**Comment by r7l** [comment]
@dtuser007 That explain. You're running the "stable" version? This isn't the most recent one. Looks like @edannenberg forgot to update the Ebuilds. You may want to switch to the `9999` version. This is the one i am running.

**Comment by dtuser007** [comment]
Yes, you are right. Seems I was not so clever :-)
I will restart my jobs here and close the issue, when all went well!
Thank you for your great support!
