### ISSUE TITLE
Support proxied / restrictive environments

### ISSUE THREAD

**Issue by Kangie** [edannenberg/kubler#238]
In the world of enterprise HPC we are often behind firewalls with limited, proxied, access to distfiles mirrors in the real world.

To support this use case, please expose the following environment variables to builders via `kubler.conf` similarly to `MIRRORS`:

- `http_proxy`
- `https_proxy`
- `no_proxy`

Note: [proxy envvars are _weird_](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/). Portage doesn't respect the uppercase versions of these variables right now, but for completeness all combinations should be set e.g. `http_proxy` and `HTTP_PROXY`.

I'm currently working around this by setting:

```
BUILDER_DOCKER_ARGS_GLOBAL=(
  '--env' 'http_proxy=proxy.server:80'
  '--env' 'https_proxy=proxy.server:80'
  '--env' 'no_proxy=localhost,127.0.0.1,.localdomain'
)
```

I think it'll be easier for the next person that comes along if there's some guidance in `kubler.conf` and sane variable names. :)

edit: `ftp_proxy` too, I guess.

**Comment by edannenberg** [comment]
Exporting those to build containers should be less of a hassle now.

**Comment by Kangie** [comment]
I updated Kubler and changed to using those... and promptly forgot about it because everything "just works". Fantastic!
