### ISSUE TITLE
missing gfortran.so

### ISSUE THREAD

**Issue by APN-Pucky** [edannenberg/kubler#243]
I get errors like this
```
error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
```
would you think putting gfortran also in the list here:

https://github.com/edannenberg/kubler/blob/4ad36ef1c7bdbe26534e1c0085b82b34ff3a729e/engine/docker/bob-core/build-root.sh#L60

Or should copy it on myself, what would you think about a `copy_gfortran_libs`?

**Comment by APN-Pucky** [comment]
Since `libquadmath.so.0` seems to be missing I think I'll PR a function `copy_gfortran_libs`. That copies those too.

**Comment by edannenberg** [comment]
Depends on the size, if they don't add too much we could just add it to `copy_gcc_libs`, otherwise your suggestion is fine and I would happily accept a PR.
