### ISSUE TITLE
universal builders and cross-compiling stuff

### ISSUE THREAD

**Issue by soredake** [edannenberg/kubler#39]
Thanks for this fantastic project, at first!
I want to add to the project support cross-compiling across different platforms, with the choice of the host architecture, with the ultimate choice of architecture which will be collected under the program. But the code in the project quite a lot, and I will leave a lot of time on understanding how it works, and adding support for cross-compilation one even longer, so I wanted to ask you, are you interested in this? If yes, would you help me to work on the support of all of this? Well, if you are not interested, then can I ask your advice as you best understand how it all works?
With your help we can make the greatest and thin containers for any architecture!

If you are interested in this, will continue to be a rough outline of what should be done:

Parameters that need to be setuped in build.sh (list is incomplete):
1) $BOB_BITS detected from list of the 32bit chosts (and change all lib64 to lib${BOB_BITS})
2) HCHOST (host chost, for build containers), needed for:
 1) build.conf (BOB_BUILDER_{CFLAGS,CHOST})
 2) bob-core/build-root.sh
 3) bob-core/portage-defaults.sh
3) TCHOST (target chost, for crossdev), needed for :
 1) build.conf (BOB_{CFLAGS,CHOST})
4) setup DEF_BUILD_CONTAINER the pass to:
 1) dock/${NAMESPACE}/build.conf
 2) build.conf
5) Final architecture alias (eg armv7a to arm), needed for universal builder containers: 
  1) ACCEPT_KEYWORDS=$ARCH
6) CFLAGS for TCHOST
7) BOB_BUSYBOX_BUILDER and BOB_BUSYBOX_CHOST created from BUILDER_ARCH (created from HCHOST)
8) multi-arch DATE in build.conf
9) update script for updating DATE

also i tried to create new format for the builders, just single file with something like here (https://github.com/azimut/gentoo-bb/commit/c332ed987d840895946ce1eb7692ad1a251aa4b3#diff-f441b4865ba6d36dc97960983d439f9fR27):

```
EMERGE_BIN="emerge${HCHOST}"
CROSSDEV_TARGET="${TCHOST}"

configure_bob() {
    if [ "${HCHOST}" == "15453654" ]; then
       do something that this host chost need
    fi
    fi [ "${TCHOST}"  == "d565665" ]; then
       do something that this target chost is need
    fi
    crossdev -S --init-target --target ${TCHOST}
    mkdir -p /usr/${CROSSDEV_TARGET}/etc/portage/package.{mask,unmask,use,keywords} /usr/${TCHOST}/tmp/
    rm /usr/${TCHOST}/etc/portage/make.profile
    ln -s /usr/portage/profiles/hardened/linux/${LIBC}/${ARCH}/${ARCH_FROM_CHOST} /usr/${TCHOST}/etc/portage/make.profile

    head -n -3 /etc/portage/make.conf > /usr/${TCHOST}/etc/portage/make.conf
    sed -i '7i CHOST=${TCHOST} \
CC=${CHOST}-gcc \
CFLAGS="-O2 -pipe -march=${BOB_CFLAGS}" \
CBUILD=${HCHOST} \
HOSTCC=${HCHOST}-gcc \
ROOT=/usr/${TCHOST}/ \
ACCEPT_KEYWORDS="*" \
PORTAGE_TMPDIR=${ROOT}tmp/ \
PKG_CONFIG_PATH="${ROOT}usr/lib/pkgconfig/" \
PKGDIR="/packages/${TCHOST}"' /usr/${TCHOST}/etc/portage/make.conf

    sed -i -e 's/^ACCEPT_KEYWORDS=" ~"/ACCEPT_KEYWORDS="${ARCH}"/g' /usr/${TCHOST}/etc/portage/make.conf

    # quick'n'dirty workaround as libsanitize currently breaks the tool chain build
    echo "cross-${TCHOST}/gcc -sanitize" > /etc/portage/package.use/gcc

    # init portage env defaults..
    source /etc/profile
    # ..but unset CHOST as it overrides make.conf
    if [ "${HCHOST}" != "${TCHOST}" ]
        unset CHOST CC CFLAGS CXXFLAGS
    else
        unset  CC CFLAGS CXXFLAGS
     fi
}
```

same for universal images:

```
configure_bob() { 
   if [ "${HCHOST}" == "15453654" ]; then
       do something that this host chost need
    fi
    fi [ "${TCHOST}"  == "d565665" ]; then
       do something that this target chost is need
    fi
}
```

for universal {images,builders} we need ability to save and run builders and images with names like gentoobb-builder-$TCHOST-$DATE for builders and gentoobb-$IMAGENAME-$TCHOST-$DATE for images.

Also still have to make many other changes to make it all work.

I am sorry that the text is so badly drafted, I did not fully understand how it works, and I wrote it all the dead of night.

Oh, and most importantly, the branch in which I am slowly starting to work on it all:
https://github.com/soredake/gentoo-bb/tree/universal

**Comment by edannenberg** [comment]
Sorry for the delay, fairly busy at the moment. I'll try to look at this a bit closer by the weekend.

**Comment by edannenberg** [comment]
Still very limited on time, sorry. Most of the changes look fairly straight forward, but I'm a bit sceptical about being able to get a fully generic cross compiling build process. The big problem being the 2nd build phase where potentially Docker will try to execute cross compiled code on a differing host architecture. (See the referenced arm PR for more details) There are workarounds for that as shown in that PR, but these are most likely always specific for any given architecture. That being said I would recommend focusing on one architecture which you could maintain in a separate git repo a long with some reference images. If you see any general improvements for cross compiling, PR's are of course welcome.

Feel free to ask for advice if you get stuck or things are unclear.

**Comment by soredake** [comment]
>Sorry for the delay
It's okay, I see https://github.com/edannenberg/gentoo-bb/issues/43, if there will be more documentation, it will be simpler to me the process of understanding how it all works, thanks anyway.
>The big problem being the 2nd build phase where potentially Docker will try to execute cross compiled code on a differing host architecture
But I think it's worth a try (in worst case it's possible to use qemu), could you show me an example of where the code is executed for a different architecture?

**Comment by azimut** [comment]
@soredake anything on the Dockerfile(.template) of an "image" will run on the target container. In this case the arm one.

**Comment by soredake** [comment]
@azimut it can be avoidable by moving RUN section of Dockerfile to runtime scripts.

**Comment by azimut** [comment]
@soredake true, also some of those (cp, ln, chmod) could be put on the builder hooks (Buildconfig.sh) too.

**Comment by edannenberg** [comment]
> it can be avoidable by moving RUN section of Dockerfile to runtime scripts

Yes, but sooner then later you will have the need to run something in the whole image context with all its parents. At this point a generic cross compiling solution won't be trivial. I'm not saying it's not doable, but I would start with a single cross target that you actually use, make it good and then start looking into making it generic. It will most likely involve some sort of helpers that need to be implemented for each cross target.

**Comment by azimut** [comment]
Another thing missing for crosscompilation is being able to copy the libraries (.so) and headers (.h) to the /usr/<ARCH>/ directory so next emerge-ARCH would find it. Might be if bob-builder.sh would run sequentially on a loop from PACKAGES we could add that cp.

Otherwise now when i complete the build of skalibs and try to compile execlib, execlib cannot find the headers for skealibs.
