### ISSUE TITLE
Simple way to skip image in namespace

### ISSUE THREAD

**Issue by berney** [edannenberg/kubler#67]
I found a simple way to skip an image in a namespace. Simply rename it as a hidden directory by putting a `.` at the start of it's name. e.g.: -

```
cd dock/gentoobb/images/
mv cadvisor .cadvisor
```

For me I wanted to build the gentoobb namespace for learning purposes but cadvisor wasn't working, no other images depend on it as seen from the very useful https://gist.github.com/azimut/74e2702074bd179953753c360bf17a1a and I'm not interested in using cadvisor at the moment so I wanted to skip it. Not fully groking gentoo-bb yet I didn't know a way to skip an image without deleting it or creating a new namespace with all images bar the ones I wanted to skip, this trick worked. If there's a proper way to do it I think it should be added to the README.md or a FAQ, or at least commented here so others can find it.

**Comment by edannenberg** [comment]
There is a indeed a undocumented [EXCLUDE](https://github.com/edannenberg/gentoo-bb/blob/master/build.sh#L88) env. This will also allow you to quite easily shoot yourself in the foot by skipping images that are required for building other images, though for your case it should be perfectly fine:

    $ EXCLUDE=gentoobb/{cadvisor,foo} ./build.sh build gentoobb

Should do the trick, can't remember having ever used it myself though, let me know if it doesn't work. :p 

I will leave this open for the upcoming documentation rewrite.

**Comment by berney** [comment]
OK great, I thought there might be a proper way I had missed.

I tried `EXCLUDE=gentoobb/{cadvisor,foo} ./build.sh build gentoobb` and it still tries to build cadvisor, if I just do `EXCLUDE=gentoobb/cadvisor ./build.sh build gentoobb` it lists cadvisor but no build is attempted.

**Comment by edannenberg** [comment]
Yea, as I said, I haven't use this since it's implementation. :stuck_out_tongue: Took a closer look and curly braces expansion is sadly a bit special and doesn't work with variables. So `EXCLUDE` would have to be implemented as script param instead of env for this to work. `build.sh -n build gentoobb/{foo,baz}` does work for example.

**Comment by edannenberg** [comment]
`build` now supports a repeatable `--exclude` arg
