### ISSUE TITLE
Add option to remove strict and destructive-clean for flaggie in build.conf

### ISSUE THREAD

**Issue by UralZima** [edannenberg/kubler#82]
Hi. Please add an option in build.conf to disable strict and clean-destructive for flaggie. 
It often reports errors but doing it's job. For example, I need to do
update_keywords 'dev-qt/*' 
it works fine without strict and clean but reports a warning.

Thanks

**Comment by edannenberg** [comment]
I find `strict` very helpful as you get early warnings on changes etc. You can always use `flaggie` directly for a few instructions or even alter files in `/etc/portage/` manually.
