### ISSUE TITLE
musl and libressl support

### ISSUE THREAD

**Issue by azimut** [edannenberg/kubler#87]
I think one of the reasons Alpine is popular (between some people at least) is due the musl and libressl native support. And I was wondering how much, if any, support can be added here. Would any of these apply?
* bob-musl-libressl builder without images (like bob-uclibc)
* bob-musl-libressl builder with an example image (like curl)
* use bob-musl-libressl whether possible across gentoobb namespace

With the multipkg FEATURE it should be possible to support both without collisions. For 1) and 2) I have some examples I think.

**Comment by jbergstroem** [comment]
I agree that the reason Alpine is popular is its nice trade-off between simple to use and resulting image sizes. Musl definitely is a big part in keeping container sizes down; but I feel libressl might more be a flavor/opinion than part of the 'success story' (especially seeing how they just switched with 3.5). The strength about this project is that its relatively simple to switch.

I'd go so far to say that I think musl should be the default toolchain, but seeing how we lean on gentoo I don't want to venture too far off. We can always just maintain (as you say) a few different builder images.

**Comment by berney** [comment]
I have been trying to use musl as much as possible as my preferred libc and builder.

Does bob-musl-libressl need to be a builder or can it be just an image? e.g. gentoobb/libressl image be built with bob-musl, and then another image like gentoobb/curl-musl could be based off gentoobb/libressl and built with bob-musl. bob-musl is the builder and libressl and curl are just images.

One reason I switched to gentoo-bb is that it's hard to get a glibc based package to work on Alpine, so for such packages a lot of people base off debian:jessie or ubuntu. That's one of the advantages I see gentoo-bb has over alpine.

**Comment by edannenberg** [comment]
@azimut I think at least adding a `bob-musl-libre` builder for illustration purposes is a good idea, we currently only have stage3 build containers in the gentoo-bb namespace so this would be a good example for extending another build container. I'm not sure it's a good idea to mix musl/glibc images in the gentoo-bb namespace, just more potential error sources for new users IMO.

The documentation could have an in-depth example that includes usage of this builder instead. Like a step-by-step instruction on how to rice `gentoobb/nginx` for example.

> @jbergstroem said:
> I'd go so far to say that I think musl should be the default toolchain

Just a matter of testing, was pleasantly surprised that nginx pretty much just build with musl. However `go` doesn't seem to compile currently, Alpine just pulls in a binary `go` dist file.

> Does bob-musl-libressl need to be a builder or can it be just an image? e.g. gentoobb/libressl image be built with bob-musl, and then another image like gentoobb/curl-musl could be based off gentoobb/libressl and built with bob-musl. bob-musl is the builder and libressl and curl are just images.

I think the problem is that portage won't allow you to merge libressl if openssl is installed in the builder. But this could be taken care of in the `bob_configure` hook for the image and wouldn't require a `bob-libressl` builder. Same goes for `bob-musl-libressl`, now that I think about it. The only advantage making it a builder image is reuse for other images that don't depend on `gentoobb/libressl`, which in the case of libressl is not very likely.

**Comment by jbergstroem** [comment]
> @edannenberg said:
> However `go` doesn't seem to compile currently, Alpine just pulls in a binary go dist file.

Is there a bug somewhere for this?

**Comment by jbergstroem** [comment]
Suspecting [https://github.com/golang/go/issues/14851](this). Found through [this Dockerfile](https://github.com/docker-library/golang/blob/master/1.8/alpine/Dockerfile#L9..L10).

**Comment by edannenberg** [comment]
I mean emerging `go` itself:

```
>>> Emerging (1 of 1) dev-lang/go-1.7.4::gentoo
 * go-linux-amd64-bootstrap.tbz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                                                                    [ ok ]
 * go1.7.4.src.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                                                                              [ ok ]
>>> Unpacking source...
>>> Unpacking go-linux-amd64-bootstrap.tbz to /var/tmp/portage/dev-lang/go-1.7.4/work
>>> Unpacking go1.7.4.src.tar.gz to /var/tmp/portage/dev-lang/go-1.7.4/work
>>> Source unpacked in /var/tmp/portage/dev-lang/go-1.7.4/work
>>> Preparing source in /var/tmp/portage/dev-lang/go-1.7.4/work/go ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-lang/go-1.7.4/work/go ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-lang/go-1.7.4/work/go ...
 * GOROOT_BOOTSTRAP is /var/tmp/portage/dev-lang/go-1.7.4/work/go-linux-amd64-bootstrap
##### Building Go bootstrap tool.
cmd/dist
./make.bash: line 132: /var/tmp/portage/dev-lang/go-1.7.4/work/go-linux-amd64-bootstrap/bin/go: No such file or directory
```

Oddly enough the file exists. The script just does a `[ ! -x ]` check, no idea why it fails, looks good to me.

**Comment by azimut** [comment]
In this time I only build another thing with musl, varnishd. And it failed. Well no really, actually I looked first at alpine and they have patches specifically due musl, not on mainstream. So yeah, musl is also something that should live on a namespace or very cautiously be integrated on the current one.

But, yes, it can an image too that is true. But I don't know how we can make it so it won't be build by default here.

I will try to get the builder with some docs sometime next week (or when spring happens...here is summer though).

**Comment by berney** [comment]
We should report bugs upstream to gentoo and try to get ebuilds to support musl. Maybe they will need a use flag. Ideally Alpine, Gentoo, and us will be reporting upstream and get the original projects to have portable C that compiles cleanly with GLibC and Musl C.

**Comment by berney** [comment]
Gentoo has a bug tracking musl support https://bugs.gentoo.org/show_bug.cgi?id=430702. It's useful to see all the dependent bugs that are packages that have issues with musl. You can vote for it or one of the dependent bugs if its important to you.

**Comment by edannenberg** [comment]
Agreed on reporting any musl related build errors upstream, or any bugs for that matter. For the time being musl shouldn't be the default builder, it's for people that are expected to know what they are doing. We should however have some clues in the documentation on how to build musl images.

**Comment by jbergstroem** [comment]
As an aside; it's pretty amazing that Alpine is holding together seeing how much software actually breaks. They're doing a great job increasing software portability!

**Comment by azimut** [comment]
Last time I forget to mention this talk of the creator of Alpine on fosdem. Pretty much what was mentioned here but gives some context to hear it from him. https://fosdem.org/2017/schedule/event/building_a_distro_with_musl_libc/

**Comment by berney** [comment]
> As an aside; it's pretty amazing that Alpine is holding together seeing how much software actually breaks. They're doing a great job increasing software portability!

I was also impressed, I didn't realise how much was broken, how many patches they are maintaining. I hope upstream sources fix it so the patches aren't needed and I hope Gentoo borrows alpines patches so that packages build out-of-the-box with musl.

**Comment by jbergstroem** [comment]
> @berney said:
>  I hope Gentoo borrows alpines patches so that packages build out-of-the-box with musl.

Lets work together on getting them upstream instead!

**Comment by azimut** [comment]
update of sorts, I am working on a namespace that supports glibc, musl, openssl.libressl at https://github.com/azimut/rpi-cluster/tree/master/gentoo-bb/dock/kubler-spin I ended up not using the bob-musl-libressl instead I just use libressl images and change the DEFAULT_BUILDER when I need it. This plus the portageq thing seems to work for me. Need to not forget to commit the builder at least here.

![ns](https://gist.githubusercontent.com/azimut/74e2702074bd179953753c360bf17a1a/raw/c03ec6c98f25b85e21cd6d9af702d5a0c120faef/own.png)

**Comment by edannenberg** [comment]
Nice, I didn't like the thought of mixing musl/glibc in a namespace but this looks managable.

> I ended up not using the bob-musl-libressl instead I just use libressl images

Yeah, creating a builder for that is overkill, most likely only the `libressl` image would ever use it.

> and change the DEFAULT_BUILDER when I need it.

Hmm can you give some use cases where you need to switch the default builder on a regular basis? Maybe something we can improve.

**Comment by azimut** [comment]
> Hmm can you give some use cases where you need to switch the default builder on a regular basis? Maybe something we can improve.

Is based on a behaviour that I saw before. For example, one can define a [DEFAULT_BUILDER][] on his namespace. In my case the default builder is bob-musl (different stage3 to bob).

So if I want to use a different builder I have 2 options. Set BUILDER, but that will use a fresh kubler-bob builder not the one from a parent image, which is just fine for the "glibc" image. Or set the default one to bob. In which case it will build it like I want it and it will use the builder of a parent image. So I set those when I want to use a different "libc" branch than the default one.

[DEFAULT_BUILDER]: https://github.com/edannenberg/kubler/blob/master/dock/kubler/kubler.conf

**Comment by edannenberg** [comment]
Hmm setting the `IMAGE_PARENT` should be enough. The build will look for the proper parent builder based on that.

**Comment by azimut** [comment]
looking at https://github.com/edannenberg/kubler/blob/master/lib/engine/docker.sh#L435 it seems you always default to use the default_builder if this does not exists `image_exists "${parent_ns}/${builder_image}-${parent_image}"` Which is my case using a non-default builder.

**Comment by edannenberg** [comment]
I see, yea that's a problem. I'll see what I can do to improve this.

**Comment by edannenberg** [comment]
Base build container should now get properly resolved, let me know how this works for you.

**Comment by azimut** [comment]
It worked!.

Here is the portageq change on build-root.sh and the commented lines on kubler.conf.

The portageq might/will break cross compiling. Something I need to resume someday.

If I didn't comment the lines mentioned It would end up always sending CHOST  variables for glibc through "-e" parameters on the docker run of the builder. So I just set the CHOST vars on each builder/bob*/build.conf.

```diff
diff --git a/kubler.conf b/kubler.conf
index 4b5bcf4..8311cac 100644
--- a/kubler.conf
+++ b/kubler.conf
@@ -23,14 +23,14 @@ DEFAULT_BUILDER="${DEFAULT_BUILDER:-kubler/bob}"
 BOB_GENTOO_MIRRORS="${BOB_GENTOO_MIRRORS:-${MIRROR}}"
 
 # active in configure_rootfs_build() hook and during the rest of the build
-BOB_CFLAGS="${BOB_CFLAGS:--mtune=generic -O2 -pipe}"
-BOB_CXXFLAGS="${BOB_CXXFLAGS:-${BOB_CFLAGS}}"
-BOB_CHOST="${BOB_CHOST:-x86_64-pc-linux-gnu}"
+#BOB_CFLAGS="${BOB_CFLAGS:--mtune=generic -O2 -pipe}"
+#BOB_CXXFLAGS="${BOB_CXXFLAGS:-${BOB_CFLAGS}}"
+#BOB_CHOST="${BOB_CHOST:-x86_64-pc-linux-gnu}"
 
 # active in configure_bob() hook, generally only differs when using crossdev
-BOB_BUILDER_CFLAGS="${BOB_BUILDER_CFLAGS:-${BOB_CFLAGS}}"
-BOB_BUILDER_CXXFLAGS="${BOB_BUILDER_CXXFLAGS:-${BOB_CXXFLAGS}}"
-BOB_BUILDER_CHOST="${BOB_BUILDER_CHOST:-${BOB_CHOST}}"
+#BOB_BUILDER_CFLAGS="${BOB_BUILDER_CFLAGS:-${BOB_CFLAGS}}"
+#BOB_BUILDER_CXXFLAGS="${BOB_BUILDER_CXXFLAGS:-${BOB_CXXFLAGS}}"
+#BOB_BUILDER_CHOST="${BOB_BUILDER_CHOST:-${BOB_CHOST}}"
 
 BOB_FEATURES="${BOB_FEATURES:-parallel-fetch nodoc noinfo noman binpkg-multi-instance}"
 BOB_EMERGE_DEFAULT_OPTS="${BOB_EMERGE_DEFAULT_OPTS:--b -k}"
diff --git a/lib/bob-core/build-root.sh b/lib/bob-core/build-root.sh
index 6c54bc8..735efb5 100755
--- a/lib/bob-core/build-root.sh
+++ b/lib/bob-core/build-root.sh
@@ -37,15 +37,18 @@ readonly _DOC_FOOTER_INCLUDES="${_ROOTFS_BACKUP}/doc.footer.includes"
 _emerge_bin="${BOB_EMERGE_BIN:-emerge}"
 _emerge_opt="${BOB_EMERGE_OPT:-}"
 
+set -x
+
 # Copy libgcc/libstdc++ libs
 function copy_gcc_libs() {
+    type -P portageq && BOB_LIB="$(portageq envvar LIBDIR_$(portageq envvar ARCH))" || BOB_LIB=$BOB_LIB
     local lib_gcc lib_stdc lib
-    mkdir -p "${_EMERGE_ROOT}"/lib64
+    mkdir -p "${_EMERGE_ROOT}"/$BOB_LIB
     lib_gcc="$(find /usr/lib/ -name libgcc_s.so.1)"
     lib_stdc="$(find /usr/lib/ -name libstdc++.so.6)"
 
     for lib in "${lib_gcc}" "${lib_stdc}"; do
-        cp "${lib}" "${_EMERGE_ROOT}"/lib64/
+        cp "${lib}" "${_EMERGE_ROOT}"/$BOB_LIB/
     done
 }
 
@@ -461,6 +464,8 @@ function build_rootfs() {
     # when using a crossdev alias unset CHOST and PKGDIR to not override make.conf
     [[ "${_emerge_bin}" != "emerge" ]] && unset CHOST PKGDIR
 
+    type -P portageq && BOB_LIB="$(portageq envvar LIBDIR_$(portageq envvar ARCH))" || BOB_LIB=$BOB_LIB
+
     if [ -n "${_packages}" ]; then
 
         generate_package_installed ${_packages}
@@ -483,8 +488,8 @@ function build_rootfs() {
             find "${_EMERGE_ROOT}/usr/include" -type f -name '*.h' | \
                 tar -cpf "${_ROOTFS_BACKUP}/${target_id//\//_}-headers.tar" --files-from -
         fi
-        if [[ -d "${_EMERGE_ROOT}/usr/lib64" ]]; then
-            find "${_EMERGE_ROOT}/usr/lib64" -type f -name '*.a' | \
+        if [[ -d "${_EMERGE_ROOT}/usr/$BOB_LIB" ]]; then
+            find "${_EMERGE_ROOT}/usr/$BOB_LIB" -type f -name '*.a' | \
                 tar -cpf "${_ROOTFS_BACKUP}/${target_id//\//_}-static_libs.tar" --files-from -
         fi
 
@@ -516,14 +521,14 @@ function build_rootfs() {
 
     # clean up
     if [ -z "${BOB_SKIP_LIB_CLEANUP}" ]; then
-        for lib_dir in "${_EMERGE_ROOT}"/{lib64,usr/lib64}; do
+        for lib_dir in "${_EMERGE_ROOT}"/{$BOB_LIB,usr/$BOB_LIB}; do
             [[ -d "${lib_dir}" ]] && find "${lib_dir}" -type f \( -name '*.[co]' -o -name '*.prl' \) -delete
         done
     fi
 
     rm -rf \
         "${_EMERGE_ROOT}"/etc/ld.so.cache \
-        "${_EMERGE_ROOT}"/usr/lib64/qt*/mkspecs/ \
+        "${_EMERGE_ROOT}"/usr/$BOB_LIB/qt*/mkspecs/ \
         "${_EMERGE_ROOT}"/usr/share/aclocal/ \
         "${_EMERGE_ROOT}"/usr/share/gettext/ \
         "${_EMERGE_ROOT}"/usr/share/gir-[0-9]*/ \
@@ -538,13 +543,13 @@ function build_rootfs() {
 
     if [[ -z "${_keep_headers}" ]]; then
         rm -rf "${_EMERGE_ROOT}"/usr/include/* \
-               "${_EMERGE_ROOT}"/usr/lib64/pkgconfig/ \
+               "${_EMERGE_ROOT}"/usr/$BOB_LIB/pkgconfig/ \
                "${_EMERGE_ROOT}"/usr/bin/*-config \
-               "${_EMERGE_ROOT}"/usr/lib64/cmake/
+               "${_EMERGE_ROOT}"/usr/$BOB_LIB/cmake/
     fi
 
     local lib_dir
-    for lib_dir in "${_EMERGE_ROOT}"/{lib64,usr/lib64}; do
+    for lib_dir in "${_EMERGE_ROOT}"/{$BOB_LIB,usr/$BOB_LIB}; do
         if [[ -z "${_keep_static_libs}" ]] && [[ -d "${lib_dir}" ]] && [[ "$(ls -A "${lib_dir}")" ]]; then
             find "${lib_dir}"/* -type f -name "*.a" -delete
         fi
```

**Comment by edannenberg** [comment]
Hmm, Portage shouldn't use `BOB_CFLAGS` directly anymore, instead `DEF_CFLAGS` is set once for each builder:

https://github.com/edannenberg/kubler/blob/master/lib/bob-core/Dockerfile.template
https://github.com/edannenberg/kubler/blob/master/lib/bob-core/etc/profile.d/portage-defaults.sh.

But maybe it would be clearer to always explicitly set those in each builder's `build.conf`.

The lib folder change looks good to me, unless you want to create a PR for it I'll add it probably with the next monthly update. `BOB_LIB` should be renamed though, it's not an environment variable. On a side note: you can use `--debug` for any command instead of adding a `set -x` to scripts.

**Comment by azimut** [comment]
I am getting a similar issue with dependencies like before but now on build_image() I end up with the wrong "builder_commit_id" causing dependencies to be wrongly calculated (it defaults to bob).
Code around where is bad assigned:
```
        get_build_container "${image_id}" "${image_type}"
        builder_id="${__get_build_container}"

        # determine build container commit id
        builder_commit_id=""
        current_image=${image_id##*/}
        if [[ ! -z "${BUILDER}" ]]; then
            builder_commit_id="${BUILDER##*/}-${current_image}"
        elif [[ "${image_type}" == "${_IMAGE_PATH}" ]]; then
            builder_commit_id="${DEFAULT_BUILDER##*/}-${current_image}"
        fi  
```
Values I get:
```
++ build_container=kubler-spin/bob-musl-muslc
++ __get_build_container=kubler-spin/bob-musl-muslc
++ builder_id=kubler-spin/bob-musl-muslc
++ builder_commit_id=
++ current_image=libresslmusl
++ [[ ! -z '' ]]
++ [[ images/ == \i\m\a\g\e\s\/ ]]
++ builder_commit_id=bob-libresslmusl
```

**Comment by edannenberg** [comment]
Looks like a good catch to me, can't test it currently but if this fixes your issue feel free to create a PR.

**Comment by edannenberg** [comment]
Fixed the `builder_commit_id` issue, should work as expected now.
