### ISSUE TITLE
Add Tests for Images

### ISSUE THREAD

**Issue by berney** [edannenberg/kubler#89]
Further to #58 which applies to gentoo-bb source, I would like a good way of writing test cases and running tests of built images or even stacks of images. This might be out of scope for gentoo-bb. I'm not necessarily looking for gentoo-bb to be extended to cover testing images, but I'd like to share ideas on how images can be tested here and if there's good consensus it could be added to documentation.

Having good tests of images will help to ensure that changes to the templates (build.conf, build,sh, etc.) does not break the images. Some of this was touched on in the discussion in #73, in order to ensure high quality images.

I would like the test cases to be written in the namespace, probably as a subdirectory, e.g. dock/mynamespace/images/figlet/tests. Some glue to kick off testing after a build would be nice IMO, it could be calling out to an external tool. Alternatively maybe something will be kicking off gentoo-bb builds and it's next step could be kicking off testing of the images, for example an ansible playbook might have a gentoo-bb build task and a docker image test task.

I'll be updating this ticket to document solutions I think are interesting or well suited.

**Comment by edannenberg** [comment]
Agreed, as always tests also serve as documentation, in this context on how to use the images. There have been some [efforts](https://github.com/edannenberg/gentoo-bb/tree/master/docker-compose) to this, but I haven't really been able to pursue this further yet. It's not very ideal either yet as having the test case right with the image is much cleaner. IIRC the reasoning for that was testing image stacks like `riemann-influxdb-grafana`, as the images are not dependend on each other, testing this at image build time would be therefore tricky. But thats really more of an integration test that should run as a seperate process, writing "unit-tests" per image should be implemented first.

So let's sketch out how testing should work:

* optional hook/config flag with a docker-compose file `compose-test.yml` or similiar per image
* if test for image is configured run docker-compose file after the image has been built
  * some generic helpers related to ensuring the test container is up and running will probably be needed
* execute `configure_test()` hook in `build.sh` of image, this would require to source the file on the host, which may or may not be an issue, shouldn't be in theory
  * bash scripting the test is up to the user, we can probably supply some generic helpers for common use cases
* if test fails, build fails

Maybe docker-compose is overkill for single image tests, we might get away with some configurable envars to run the test image.

Curious to see what your digging brings to light, we shouldn't be the first with this problem. Unless we do some docker-in-docker stuff keep in mind that tests are run on the host, so extra dependencies just for running tests need to be carefully weighted.

**Comment by berney** [comment]
The more I think about this the more I think that proper testing should be some external tooling using the images that cooper 😋 built. Unit tests and quick tests like looking for broken linkage, and firing up in docker etc, including firing up a stack from docker-compose is good. And then more testing done outside all of this, integration testing. I still need to look further into this. I'll document what I find.

**Comment by azimut** [comment]
Might be add a HEALTHCHECK https://docs.docker.com/engine/reference/builder/#healthcheck to each image to start and then have it the build test check the status of it.

**Comment by berney** [comment]
Thanks @azimut I hadn't noticed that Dockerfile directive before.

**Comment by edannenberg** [comment]
> @berney said:
The more I think about this the more I think that proper testing should be some external tooling using the images that cooper :yum: built.

If we can avoid reinventing the wheel by using a dedicated image testing tool I'm all for it. So far I haven't seen anything though. We should probably also keep in mind that `aci/oci` bundles might be a thing soon.

> @azimut said:
Might be for functional tests, add a HEALTHCHECK

This looks very nice indeed. I will play around with that a bit.

---

Also stumbled about this [article](http://blog.jevsejev.io/2016/06/09/docker-image-tests/), combined with `HEALTHCHECK` this should be decent enough for unit tests I think.

**Comment by edannenberg** [comment]
Did some work for this over the holidays, current state:

There are 2 types of tests now:

1. Docker's `HEALTHCHECK`

If `POST_BUILD_HC` is set in a image's `build.conf` the build will run a detached container of the freshly created image and monitor it's health status for a period of time.

2. `build-test.sh`

For images where a Docker `HEALTHCHECK` doesn't make a lot of sense (i.e. bash, openssl, etc) you can add a `build-test.sh` file to your image dir. If the file exists the build will run a container of the freshly created image with the image dir mounted as `/kubler-test`. `build-test.sh` is then executed in the container and depending on the script exit signal the build fails or not.

**Comment by edannenberg** [comment]
0.9.0 release has finally landed.

**Comment by berney** [comment]
I'm not sure if the best approach is to keep adding to `kubler` functionality or to use a CI/CD system.

I tend to build distroless images that don't have a shell (`/bin/sh`). I've been experimenting with adding a new test mechanism for them that uses aelsabbahy/goss. I've experimented with different methods and at the moment I build a derived image that has goss.

I have two types of images, those that are daemons, and those that are utilities:

1. For utilities I build a derived image that add `goss` and related files (`goss.yaml` etc) and makes `goss` the entry point. This is necessary as the container will typically exit immediately before something like `dgoss` could run `goss`.

2. For daemons, I want to test the original container using a mechanism like `dgoss`, so that the running processes, listening sockets, etc. can be tested with `goss`. This is if I don't want `goss` permanently baked into the image as the `HEALTHCHECK`.
