### ISSUE TITLE
Spring is coming

### ISSUE THREAD

**Issue by edannenberg** [edannenberg/kubler#92]
Just a quick heads up for some stuff in the pipeline and to gather some feedback.

Refactoring the complete code base is pretty much done, some highlights:

* Modular command system, think Git or Docker, with a single main script and contextual help
* Portage tree and stage3 imports are now de-duplicated, see #83
* Lots of old cruft removed and many optimizations, `awk` is no longer required on the host for example
* Code base now conforms to official Bash naming/coding conventions
* All functions that previously "returned" something via `echo` now simply set a global variable `__function_name`
* To improve clarity variable types now have the following schema:
```
# variable conventions:
#
# environment     : SOME_VAR
# readonly        : _SOME_VAR
# local           : some_var
# global          : _some_var
# function return : __function_name
```

The last point is a breaking change, for example `EMERGE_ROOT` is a constant and as such is now named `_EMERGE_ROOT`. I plan this to be the last breaking refactor, so we might as well think about renaming some variables that users have to deal with like `_EMERGE_ROOT`, maybe something shorter or to improve clarity. Thoughts?

---

When this update lands (1-2 weeks) the project name will also change, I'm currently leaning towards `omnibob` (Wikipedia: Omni is a Latin prefix meaning "all" or "every".), fits the bill pretty well as it's really just a meta builder at the core. Still not decided though. Sadly `metabob` is already taken.

Other suggestions:

* cbob, as in container bob
* [cooper](https://en.wikipedia.org/wiki/Cooper_%28profession%29) by @mischief 

---

`acbuild` support and better documentation are the next 2 milestones on the list, most of the acbuild requirements are already ticked off though, so this shouldn't take too long.

A preview branch for testing should be up in the next couple days.

**Comment by jbergstroem** [comment]
Very exciting. I think we should start thinking about the bigger roadmap as well; which would include something like:
 - tests  (required before "1.0" if you ask me)
 - naming (as referred above; my vote would be cooper. It's simple to remember, doesn't sound too technical and has a backstory)
 - general website/marketing
 - community and workflow (publishing images, best practises, repo scope)

I don't think we have to solve all of this in two weeks, but we should at least figure out a timeframe. I will have more time for "open source" (read: computer time that isn't work-related) in 2 weeks and will be happy to help out in most areas.

Also, as for 'breaking' changes; I think we should be pretty laxed about breaking stuff until we hit 1.0. I gather ~5 active users and I think we all prefer improved change over legacy support.

Lets jump on a chat (voice omg?) sometime and try to plan this out?

**Comment by jbergstroem** [comment]
Oh; as for naming -- finding a word combo with said name for domain and github org repo should also be considered.

**Comment by azimut** [comment]
Where are the naming conventions documented? It looks daunting to me. Only guideline that I knew was https://google.github.io/styleguide/shell.xml#Naming_Conventions

Other than that probably you can use https://github.com/openstack-dev/bashate to clean some of the code (and start adding a test to the code)

**Comment by edannenberg** [comment]
> @jbergstroem  said:
I will have more time for "open source" (read: computer time that isn't work-related) in 2 weeks and will be happy to help out in most areas.

Yay.

> @jbergstroem said:
Also, as for 'breaking' changes; I think we should be pretty laxed about breaking stuff until we hit 1.0. I gather ~5 active users and I think we all prefer improved change over legacy support.

Agreed, but it's still annoying and now would be a very good time for any breaking changes.

> @jbergstroem said:
Lets jump on a chat (voice omg?) sometime and try to plan this out?

Sure, had a fairly busy week but should have some time this weekend. Maybe open a slack channel so everyone can chime in without having to set up a bouncer?

> @azimut said:
Where are the naming conventions documented? It looks daunting to me. Only guideline that I knew was https://google.github.io/styleguide/shell.xml#Naming_Conventions

I used the linked style guide as much as possible, the naming convention for variables I defined myself. I find the source much clearer now as a variable's scope is obvious just by looking at the name.

> @azimut said:
Other than that probably you can use https://github.com/openstack-dev/bashate to clean some of the code (and start adding a test to the code)

Looking at the checked rules the source should already be fine, but something to keep in mind when adding tests. Thanks for pointing it out.

---

Pushed current state to [spring](https://github.com/edannenberg/gentoo-bb/tree/spring) branch:

* `main.sh` is entry script for now, gonna get renamed
* `bob-interactive.sh` got replaced by `--interactive` or `-i` option for `build` command
* only `busybox` and `glibc` images are refactored currently, should only be a matter of adjusting for `_ROOT_EMERGE` and `_packages` in existing images though.
* Argbash is used for argument parsing and contextual help, see [lib/argbash](https://github.com/edannenberg/gentoo-bb/tree/spring/lib/argbash), some minor teething issue I already reported upstream:
    * `./main.sh --help` currently only displays the short help, to see the full help `./main.sh foo --help`, hopefully fixed soon

Should be fairly complete otherwise, please give it a try with your own namespaces.

**Comment by azimut** [comment]
I am trying to build busybox but I get `docker: Error response from daemon: invalid hostname format: gentoobbarm/bob-musl`

I think docker doesn't accept `/` on the hostname:

https://github.com/docker/docker/issues/23122
https://github.com/docker/docker/pull/20566/files

**Comment by azimut** [comment]
On a different note. Might be there should be Changelog to put things like the migration, changes or new features.

**Comment by azimut** [comment]
Thanks!
Just some really minor things I found while building (I removed the --hostname to keep building locally)
* add /var/lib/gentoo and /etc/portage/ to cleanup of rootfs.tar
* add the flag to skip baselayout on busybox (as it was the default behaviour before)
* might be calls to main.sh should default to the behaviour of passing it "..." that shows the full help.
So yeah, things worked great. Will need to try the portage thing as well as try to use those oci images other day.

**Comment by edannenberg** [comment]
> add /var/lib/gentoo and /etc/portage/ to cleanup of rootfs.tar

done.

> add the flag to skip baselayout on busybox (as it was the default behaviour before)

That's news to me. :P But reminds me that I did want to try a full rebuild with that flag enabled.

> might be calls to main.sh should default to the behaviour of passing it "..." that shows the full help.

That's currently an Argbash limitation, it's already reported and hopefully fixed soon. Depending on how long this takes I can also fix the generated parsing code manually.

**Comment by UralZima** [comment]
Hello. I just found where the real work is going :) I thought master is default dev branch. 
I have updated to spring and have issue and questions. 
1. When building s6, it failed on RUN with '/etc/service/.s6-svscan' not found error. Don't know why. I just added mkdir /etc/service/.s6-svscan on beginning of RUN and all went fine.
2. I modified my default CFLAGS in build.conf, and added -march=native (php use 25% less memory with that, and makes executables a bit faster). When I exec bash in bob, I don't see them in make.conf, and $CFLAGS, only $DEF_CFLAGS and $BOB_CFLAGS. Is this working? I don't know how to test executables and their compiler params
3. I think default make.conf from lib/bob-core must be moved to rootdir
4. I had some hacks modifying ebuilds, now they are not working, coz on building seems /usr/portage is not mounted. I use this:
      sed -i 's/php7-0/php7-1/g' /usr/portage/dev-php/pecl-geoip/pecl-geoip-1.1.1-r2.ebuild
      ebuild /usr/portage/dev-php/pecl-geoip/pecl-geoip-1.1.1-r2.ebuild digest
because it is not building for php7.1
How to port this now to new version of gentoobb?

Thanks

**Comment by edannenberg** [comment]
> 1. When building s6, it failed on RUN with '/etc/service/.s6-svscan' not found error. Don't know why. I just added mkdir /etc/service/.s6-svscan on beginning of RUN and all went fine.

I haven't refactored all the images in the branch yet, only busybox and glibc, so yea the other images might have some minor issues. At the very least you need to change to `_EMERGE_ROOT` and `_packages` for the other images.

> 2. I modified my default CFLAGS in build.conf, and added -march=native (php use 25% less memory with that, and makes executables a bit faster). When I exec bash in bob, I don't see them in make.conf, and $CFLAGS, only $DEF_CFLAGS and $BOB_CFLAGS. Is this working? I don't know how to test executables and their compiler params

Try changing the flags of the builder's `build.conf`, it most likely overrides the values from global/namespace `build.conf`. This was needed for supporting multiple stage3 builders, so not really related to this branch. Also keep in mind that changing `CFLAGS` requires a rebuild of the builder now to take effect.

> 3. I think default make.conf from lib/bob-core must be moved to rootdir

Not sure I understand the problem, need more details.

> 4. I had some hacks modifying ebuilds, now they are not working, coz on building seems /usr/portage is not mounted. 

Default portage location is now `/var/sync/portage`. Had to move it out of `/usr` to enable deleting the portage dir when switching to git sync and a `/usr` volume on the portage container is not a good idea for obvious reasons. Open for better path suggestions though.

**Comment by UralZima** [comment]
1. About CFLAGS. I just wanted to ask, if it is working this way. I modified them in global build.conf and need them anywhere. Just the usual way is define them in make.conf, so I wanted to ask, if GCC uses these DEF_CFLAGS variables or if bob passes it to GCC

2. About moving make.conf
> Not sure I understand the problem, need more details.
I mean  you made new tree structure, where all core parts you put in lib dir, etc it is all good, config files remain in root directory. But make.conf maybe changed by user, it is also a config file, and I think it's better place near other config files (build.conf and run.conf). And add all them to .gitignore by default, so I can safely git pull.

3. You can remove 
BOB_SYNC_URI="${BOB_SYNC_URI:-rsync://rsync.europe.gentoo.org/gentoo-portage}"
BOB_SYNC_TYPE="${BOB_SYNC_TYPE:-rsync}"
They are not working anymore. I am not sure someone will prefer rsync instead of current default git. 

4. I had problems with your default Dresden mirrors, many 404 not found errors. So I changed 
BOB_GENTOO_MIRRORS="${BOB_GENTOO_MIRRORS:-http://distfiles.gentoo.org/}"
and I think it must be default for all users.

5. I use gentoobb on hardened gentoo with grsecurity, zfs etc. I use bash as my source package for many packages. So I added 'paxctl' package to bash, and wanted it to be available on all images it depends on. But it is not available on next images. Can you please explain, how emerge actually works? Why it install some packages to /, some to /emerge-root, or both 2 times. Why php need to be installed in configure_bob first, and then usual way, and many other packages that fail. I just want to understand how this process works to avoid errors in the future.

**Comment by azimut** [comment]
my 2cents about 4) would be that this projects uses the (not very well documented) --root option of emerge. The best docs i found were at https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/portage-build-faq basically emerges on /emerge-root the RDEPEND and not the DEPEND (though they might be the same sometimes) https://devmanual.gentoo.org/general-concepts/dependencies/ You have a flag --root-rdepend when you can push the DEPEND on ROOT too apparently.

The other thing in this project is that the builder of the parent image is actually re-used for the child one. Unless you set a custom builder on build.conf for your image.

**Comment by edannenberg** [comment]
> But make.conf maybe changed by user, it is also a config file, and I think it's better place near other config files (build.conf and run.conf). And add all them to .gitignore by default, so I can safely git pull.

I see, the default [make.conf](https://github.com/edannenberg/gentoo-bb/blob/spring/lib/bob-core/etc/portage/make.conf) is very bare bone and can be customized or even completely replaced by any builder. You could `echo "foo" >>` some lines, sed stuff or place your own `make.conf` in a builder dir and add `COPY make.conf /etc/portage/` to the builder's `Dockerfile.template`. Keep in mind that we configure many of Portage's features via [env script](https://github.com/edannenberg/gentoo-bb/blob/spring/lib/bob-core/etc/profile.d/portage-defaults.sh). Other then that there are no limits how a builder wants to configure itself.

>2. You can remove BOB_SYNC_URI= ....

Yea, can probably be removed. 

> 3. I had problems with your default Dresden mirrors, many 404 not found errors. So I changed
BOB_GENTOO_MIRRORS="${BOB_GENTOO_MIRRORS:-http://distfiles.gentoo.org/}"
and I think it must be default for all users.

Fair point, maybe disable the variable's default and use `mirror-select` as part of builder setup?

> 4. So I added 'paxctl' package to bash, and wanted it to be available on all images it depends on. But it is not available on next images.

How did you add the package? If it was via `_packages` then it should be available for depending images.

> Can you please explain, how emerge actually works? Why it install some packages to /, some to /emerge-root, or both 2 times. Why php need to be installed in configure_bob first, and then usual way, and many other packages that fail. I just want to understand how this process works to avoid errors in the future.

To fully understand this just have a look at [build-root.sh](https://github.com/edannenberg/gentoo-bb/blob/spring/lib/bob-core/build-root.sh#L385). The script is the only command executed when the build container is started during a build. As part of its flow it executes the functions you defined in your builder's/image's `build.sh`.

* `configure_bob` => emerge installs packages in the build container's `/` as usual
* After that the `ROOT` env is [set](https://github.com/edannenberg/gentoo-bb/blob/spring/lib/bob-core/build-root.sh#L414) to `/emerge-root`, this is equivalent to passing `--root` to `emerge`
* Hence all emerge calls in `configure_rootfs_build` and `finish_rootfs_build` hooks will install/delete packages at the custom root
* Some packages have problems building when using `--root`, most of the time this comes down to dependencies that are required during build time not being found by the build, because they only exist at the custom root while the build expects them at the build container's root. To work around that you install the package in `configure_bob` first, which also generates a binary package. This binary package is then used when installing at the custom root, circumventing all build troubles. A more elegant way is to simply install the needed build time dependencies in `configure_bob` hook, but this may require a bit more fiddling.

And that's pretty much all there is to it.

**Comment by UralZima** [comment]
@edannenberg, thanks for your answer. Now it is more clear. About mirrors, I never use them and never trust them. You depend from one more server/admin. But it's my opinion :) Don't like to receive 404 unexpectedly, if someone forget to sync with master. Maybe keep default and allow user to choose mirror, if he like.

I have 2 more issues. 
1. If build.sh uses layman to add a repo, and build fails, next try build will fail with 'repo already added'. Ok I modified my line to:
layman -a rindeal || true
But package was not found, even repo is added. 
So I do 
layman -d rindeal || true
layman -a rindeal || true
and only now it works.

2. I am building phantomjs-2.1.1 and build fails on libxcb-1.12-r2, saying No Python implementation found for the build. I checked in interactive mode, I have 2 pythons and all of them working. What can be the issue?

**Comment by UralZima** [comment]
Here is the log:
 
* Package:    x11-libs/libxcb-1.12-r2
 * Repository: gentoo
 * Maintainer: x11@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU xkb
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
 * No Python implementation found for the build. This is usually
 * a bug in the ebuild. Please report it to bugs.gentoo.org
 * along with the build log.

 * ERROR: x11-libs/libxcb-1.12-r2::gentoo failed (setup phase):
 *   No supported Python implementation installed.
 * 
 * Call stack:
 *               ebuild.sh, line 115:  Called pkg_setup
 *   libxcb-1.12-r2.ebuild, line  42:  Called python-any-r1_pkg_setup
 *    python-any-r1.eclass, line 343:  Called python_setup
 *    python-any-r1.eclass, line 331:  Called die
 * The specific snippet of code:
 *      die "No supported Python implementation installed."
 * 
 * If you need support, post the output of `emerge --info '=x11-libs/libxcb-1.12-r2::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=x11-libs/libxcb-1.12-r2::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/x11-libs/libxcb-1.12-r2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/x11-libs/libxcb-1.12-r2/temp/die.env'.
 * Working directory: '/var/tmp/portage/x11-libs/libxcb-1.12-r2/homedir'
 * S: '/var/tmp/portage/x11-libs/libxcb-1.12-r2/work/libxcb-1.12'
~

**Comment by edannenberg** [comment]
> If build.sh uses layman to add a repo, and build fails, next try build will fail with 'repo already added'.

Yep, that's because the layman overlay dir is now a volume of the portage container and shared with all build containers. I did a similiar [check](https://github.com/edannenberg/gentoo-bb/blob/spring/dock/gentoobb/builder/bob-musl/build.sh#L38) for the musl build container. Will probably wrap layman with a small function that won't fail if a overlay already exists on add.

> I am building phantomjs-2.1.1 and build fails on libxcb-1.12-r2.. What can be the issue?

Builds fine for me, including phantomjs:

```
>>> x11-libs/libxcb-1.12 merged
```

Try building in an interactive build container, check if python install is correct etc.

**Comment by UralZima** [comment]
I was building it on top of php7. It has multiple x11-*/* in package.provided. I removed them all with sed '/x11/d' and build went fine. 
I had issues with libpcre. it was listed in provided, but I enabled use flag '+pcre16'. it was not rebuilt, and qtgui build failed. So I unprovided it. 

Is there any way to remember use flags in packages.provided, and rebuild if mismatch? I think it will resolve many portage issues and will make preparing packages much easier. What do you think?

**Comment by UralZima** [comment]
Summer is coming: https://github.com/edannenberg/gentoo-bb/issues/102

**Comment by edannenberg** [comment]
A quick update:

1. After much consideration the new project name is now set in stone: `kubler`. It's a play on `Kübler`, which is a traditional german surname that has it's origin in the cooper profession. Much like Miller or Smith. Thank you @mischief for the `cooper` suggestion.

2. `kubler.sh` can now be put into the system `PATH`, symlinked is fine too, and called from any sub folder of a namespace. Single and multi namespace formats are supported and can exist outside of Kubler's project folder. Creating an install procedure should be trivial now, though I still don't see much use for that. However there will be release zip files that don't include the example images.

Main work should be done for this branch, current plan is to merge this into master with the next monthly update, so 1-2 weeks. I'll update the branch with detailed changelog in the next couple days.

---

> @UralZima said:
Is there any way to remember use flags in packages.provided, and rebuild if mismatch? I think it will resolve many portage issues and will make preparing packages much easier. What do you think?

`package.provided` only lists specific package atoms that should be considered as installed, so no it's not possible.

**Comment by edannenberg** [comment]
New branch is up, changelog:

* Refactor project for name change gentoo-bb -> kubler
* `kubler.sh` now behaves like a regular CLI app that can be put into `PATH`
* Rename global and namespace `build.conf` to `kubler.conf`
* Add support for external `--working-dir` that only contains namespaces(multi) or images(single)
* If `--working-dir` is not defined try to detect a proper working dir starting from PWD
* If PWD is inside a valid namespace dir the namespace part of image ids can be omitted, i.e. just build busybox
* Source `build-root.sh` and `/etc/profile` on interactive build container start. Make helper functions avail.
* Rename CONTAINER_ENGINE -> BUILD_ENGINE in all namespace config files
* Manually massage generated Argbash code to be release ready
* Fix few subtle regression bugs
* Apply lots of polish all over the place
* Prepare for monthly stack update, minor fixes and full rebuild

To create an external working dir just `cd` into some directory where you would like to create the working dir and run `kubler new namespace foo`. The helper should explain everything else.

Baring any bugs this should be close to release quality and merged into master next week, maybe a bit sooner depending how the tests go.

I have updated the `README.md` for the most part, if any of our fluent English speakers could proof read and PR, that would be :+1:. I have left a 2nd draft version of the initial paragraphs in the `README.md` feel free to expand/rework, a bit stuck and not entirely happy with the silly version, but could potentially be good I think.

This is a fairly large commit again, might have missed a few things to mention. I did however do a complete stack rebuild and everything seems to be in order. Please test (ideally with a fresh clone) and let me know if there are any issue left. Specially any error messages that should have more meaningful output.

As I had to rebase to get some fixes from master, the latest and greatest is now in the [kubler](https://github.com/edannenberg/gentoo-bb/tree/kubler) branch.

**Comment by berney** [comment]
I like the new name, this quote you put in the new branches readme is great: -
> Wikipedia said: There is still demand for high-quality ~wooden barrels~ containers, and it is thought that the highest-quality ~barrels~ containers are those hand-made by professional coopers kublers

**Comment by edannenberg** [comment]
Last bugs should be squashed, git repo is renamed and everything got merged into master. :tada: Monthly image update is pushed to new [kubler](https://hub.docker.com/u/kubler/) docker hub account. I'll leave the old account up for a bit longer.

To update existing gentoo-bb git repos:

    git remove -v show
    git remote set-url origin https://github.com/edannenberg/kubler.git
    git remove -v show

**Comment by jbergstroem** [comment]
> @edannenberg said:
> Monthly image update is pushed to new kubler docker hub account

We should automate this. Perhaps kickstart things over at travis to rebuild?

**Comment by berney** [comment]
@edannenberg should:
> `git remove -v show`

be `git remote -v show`?
