### ISSUE TITLE
Idea: replace layman with simple shell function

### ISSUE THREAD

**Issue by soredake** [edannenberg/kubler#93]
```
sync_overlay() {
    repop="/var/lib/repos"
    [ ! -d "$repop" ] && mkdir -p "$repop"
    tee /etc/portage/repos.conf/"$1".conf >/dev/null <<END
[$1]                                                                    
priority = 50                                                      
location = $repop/$1                                                   
sync-type = git
sync-uri = $2                                                     
END
    emaint sync -r "$1" 
}          
```
`sync_overlay musl https://anongit.gentoo.org/git/proj/musl.git`

**Comment by jbergstroem** [comment]
Potentially stupid question: Is git pre-installed in the builders?

**Comment by soredake** [comment]
@jbergstroem https://github.com/edannenberg/gentoo-bb/blob/master/dock/gentoobb/builder/bob/build.sh#L26

**Comment by jbergstroem** [comment]
Good (note to self: i really need to spend more time with this project :( )

**Comment by edannenberg** [comment]
I wouldn't replace layman, but more options are always nice. Maybe this would be better as a separate script in [lib/bob-core](https://github.com/edannenberg/gentoo-bb/tree/spring/lib/bob-core) named `portage-add-overlay.sh`.
