### ISSUE TITLE
Idea: source helpers to bob_interactive.sh

### ISSUE THREAD

**Issue by azimut** [edannenberg/kubler#96]
It might be helpful have the helpers defined in the current build-root at bob_interactive.sh. We can just source build-root but we need to change it to support it. Like using BASH_SOURCE to detect when is being sourced and don't perform any action (return 0)

Additionaly add a help() to list the helpers at least can help too.

**Comment by edannenberg** [comment]
Hmm interesting. Putting some helpers that are useful into separate shell scripts might also be an option. Maybe all with `bob-` prefix for tab-tab discovery. Can you describe some use cases for this?

As for documenting the helpers, I think the recently added boiler plate helpers can solve this quite well by adding lots of examples with notes to the created [build.sh](https://github.com/edannenberg/gentoo-bb/blob/spring/lib/template/docker/image/build.sh)

**Comment by azimut** [comment]
When I want to build a new image now I use bob_interactive and start doing a: `ROOT=/somedir emerge -D --tree -vp somepackageatom`. So I could see the dependency tree the package is going to pull. And if in the tree I glance something I don't like (for example pulling a dependency I don't want due a USE flag). I just run the helper and retry. When I am happy with the results I do "history" and copy the commands I run on configure_bob() of the new image.

So right now I just copy manually the functions I want. But if the env had it already and even remind me of the helpers that I can use it would help. Again, I can always use echo to portage. But the helpers make build.sh cleaner i think.

**Comment by azimut** [comment]
oh, also I added equery to my builder. It's really helpful (though there are other ways to get the flags the colors help)

**Comment by edannenberg** [comment]
I've refactored `build-root.sh` a bit:

* `build-root.sh` can now be sourced, moved out of `PATH`
* added a thin wrapper function `kubler_build_rootfs` for starting the rootfs build in interactive mode
  * `rootfs.tar` and `PACKAGES.md` are not created at the end of the build
  * `/emerge-root` is not deleted to allow inspection
* interactive builds now source `/etc/profile` and `build-root.sh` via `.bashrc`

> But if the env had it already and even remind me of the helpers that I can use it would help.

I was thinking about giving helper functions a common prefix like `kubler_update_use`, this would allow `<tab><tab>` discovery in the interactive container. Downside is a bit longer function names and image breakage. What do you guys think?

**Comment by edannenberg** [comment]
I think it's pretty usable now, if we want to go the extra mile:

* Rename helper functions with a prefix like `kubler_` or `kbr_`. Could also add some convenience wrappers.
* Add `--help` functionality to each helper function like `update_use`

@azimut please give it a try and let me know how this works for you

**Comment by azimut** [comment]
Looks good! I can see myself using "declare -F/-f" to remind myself which ones are available and what they do. Might be we can just use that and a internal variable with the help to someone using declare?.

Though I see the value of the wrappers and --help I think this is good enough to write a guide or orient people about portage.
